// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: like.proto

package likeservice

import (
	"context"

	"sea-try-go/service/like/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetLikeCountReq        = pb.GetLikeCountReq
	GetLikeCountResp       = pb.GetLikeCountResp
	GetLikeStateReq        = pb.GetLikeStateReq
	GetLikeStateResp       = pb.GetLikeStateResp
	GetTargetLikerListReq  = pb.GetTargetLikerListReq
	GetTargetLikerListResp = pb.GetTargetLikerListResp
	GetUserLikeListReq     = pb.GetUserLikeListReq
	GetUserLikeListResp    = pb.GetUserLikeListResp
	GetUserTotalLikeReq    = pb.GetUserTotalLikeReq
	GetUserTotalLikeResp   = pb.GetUserTotalLikeResp
	LikeActionReq          = pb.LikeActionReq
	LikeActionResp         = pb.LikeActionResp
	LikeCountItem          = pb.LikeCountItem
	LikeItem               = pb.LikeItem
	LikeRecordItem         = pb.LikeRecordItem

	LikeService interface {
		LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionResp, error)
		GetLikeCount(ctx context.Context, in *GetLikeCountReq, opts ...grpc.CallOption) (*GetLikeCountResp, error)
		GetLikeState(ctx context.Context, in *GetLikeStateReq, opts ...grpc.CallOption) (*GetLikeStateResp, error)
		GetUserLikeList(ctx context.Context, in *GetUserLikeListReq, opts ...grpc.CallOption) (*GetUserLikeListResp, error)
		GetTargetLikerList(ctx context.Context, in *GetTargetLikerListReq, opts ...grpc.CallOption) (*GetTargetLikerListResp, error)
		GetUserTotalLike(ctx context.Context, in *GetUserTotalLikeReq, opts ...grpc.CallOption) (*GetUserTotalLikeResp, error)
	}

	defaultLikeService struct {
		cli zrpc.Client
	}
)

func NewLikeService(cli zrpc.Client) LikeService {
	return &defaultLikeService{
		cli: cli,
	}
}

func (m *defaultLikeService) LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionResp, error) {
	client := pb.NewLikeServiceClient(m.cli.Conn())
	return client.LikeAction(ctx, in, opts...)
}

func (m *defaultLikeService) GetLikeCount(ctx context.Context, in *GetLikeCountReq, opts ...grpc.CallOption) (*GetLikeCountResp, error) {
	client := pb.NewLikeServiceClient(m.cli.Conn())
	return client.GetLikeCount(ctx, in, opts...)
}

func (m *defaultLikeService) GetLikeState(ctx context.Context, in *GetLikeStateReq, opts ...grpc.CallOption) (*GetLikeStateResp, error) {
	client := pb.NewLikeServiceClient(m.cli.Conn())
	return client.GetLikeState(ctx, in, opts...)
}

func (m *defaultLikeService) GetUserLikeList(ctx context.Context, in *GetUserLikeListReq, opts ...grpc.CallOption) (*GetUserLikeListResp, error) {
	client := pb.NewLikeServiceClient(m.cli.Conn())
	return client.GetUserLikeList(ctx, in, opts...)
}

func (m *defaultLikeService) GetTargetLikerList(ctx context.Context, in *GetTargetLikerListReq, opts ...grpc.CallOption) (*GetTargetLikerListResp, error) {
	client := pb.NewLikeServiceClient(m.cli.Conn())
	return client.GetTargetLikerList(ctx, in, opts...)
}

func (m *defaultLikeService) GetUserTotalLike(ctx context.Context, in *GetUserTotalLikeReq, opts ...grpc.CallOption) (*GetUserTotalLikeResp, error) {
	client := pb.NewLikeServiceClient(m.cli.Conn())
	return client.GetUserTotalLike(ctx, in, opts...)
}
