// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content_security.proto

package contentsecurityservice

import (
	"context"

	"sea-try-go/service/content_security/rpc/pb/sea-try-go/service/content-security/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SanitizeContentRequest  = pb.SanitizeContentRequest
	SanitizeContentResponse = pb.SanitizeContentResponse
	SanitizeOptions         = pb.SanitizeOptions

	ContentSecurityService interface {
		SanitizeContent(ctx context.Context, in *SanitizeContentRequest, opts ...grpc.CallOption) (*SanitizeContentResponse, error)
	}

	defaultContentSecurityService struct {
		cli zrpc.Client
	}
)

func NewContentSecurityService(cli zrpc.Client) ContentSecurityService {
	return &defaultContentSecurityService{
		cli: cli,
	}
}

func (m *defaultContentSecurityService) SanitizeContent(ctx context.Context, in *SanitizeContentRequest, opts ...grpc.CallOption) (*SanitizeContentResponse, error) {
	client := pb.NewContentSecurityServiceClient(m.cli.Conn())
	return client.SanitizeContent(ctx, in, opts...)
}
