// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: follow.proto

package server

import (
	"context"

	"sea-try-go/service/follow/rpc/internal/logic"
	"sea-try-go/service/follow/rpc/internal/svc"
	"sea-try-go/service/follow/rpc/pb"
)

type FollowServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFollowServiceServer
}

func NewFollowServiceServer(svcCtx *svc.ServiceContext) *FollowServiceServer {
	return &FollowServiceServer{
		svcCtx: svcCtx,
	}
}

// 1. 点击关注 (O(1) 插入边)
func (s *FollowServiceServer) Follow(ctx context.Context, in *pb.RelationReq) (*pb.BaseResp, error) {
	l := logic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

// 2. 取消关注 (O(1) 删除边)
func (s *FollowServiceServer) Unfollow(ctx context.Context, in *pb.RelationReq) (*pb.BaseResp, error) {
	l := logic.NewUnfollowLogic(ctx, s.svcCtx)
	return l.Unfollow(in)
}

// 3. 拉入黑名单 (O(1) 插入边并清理双向 Follow 边)
func (s *FollowServiceServer) Block(ctx context.Context, in *pb.RelationReq) (*pb.BaseResp, error) {
	l := logic.NewBlockLogic(ctx, s.svcCtx)
	return l.Block(in)
}

// 4. 拉出黑名单 (O(1) 删除边)
func (s *FollowServiceServer) Unblock(ctx context.Context, in *pb.RelationReq) (*pb.BaseResp, error) {
	l := logic.NewUnblockLogic(ctx, s.svcCtx)
	return l.Unblock(in)
}

// 5. 获取关注列表 (O(K), K 为 limit)
func (s *FollowServiceServer) GetFollowList(ctx context.Context, in *pb.ListReq) (*pb.UserListResp, error) {
	l := logic.NewGetFollowListLogic(ctx, s.svcCtx)
	return l.GetFollowList(in)
}

// 6. 获取黑名单列表 (O(K))
func (s *FollowServiceServer) GetBlockList(ctx context.Context, in *pb.ListReq) (*pb.UserListResp, error) {
	l := logic.NewGetBlockListLogic(ctx, s.svcCtx)
	return l.GetBlockList(in)
}

// 7. 获取粉丝列表 (O(K))
func (s *FollowServiceServer) GetFollowerList(ctx context.Context, in *pb.ListReq) (*pb.UserListResp, error) {
	l := logic.NewGetFollowerListLogic(ctx, s.svcCtx)
	return l.GetFollowerList(in)
}

// 8. 遍历三层关系查找可能喜欢 (受限 BFS)
func (s *FollowServiceServer) GetRecommendations(ctx context.Context, in *pb.ListReq) (*pb.RecommendResp, error) {
	l := logic.NewGetRecommendationsLogic(ctx, s.svcCtx)
	return l.GetRecommendations(in)
}
