// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/comment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 参考B站设计用枚举类型表示某条评论的状态
type CommentState int32

const (
	CommentState_STATE_NORMAL    CommentState = 0 //正常
	CommentState_STATE_REVIEWING CommentState = 1 //审核中
	CommentState_STATE_DELETED   CommentState = 2 //评论被删除
	CommentState_STATE_BLOCKED   CommentState = 3 //评论被封禁
)

// Enum value maps for CommentState.
var (
	CommentState_name = map[int32]string{
		0: "STATE_NORMAL",
		1: "STATE_REVIEWING",
		2: "STATE_DELETED",
		3: "STATE_BLOCKED",
	}
	CommentState_value = map[string]int32{
		"STATE_NORMAL":    0,
		"STATE_REVIEWING": 1,
		"STATE_DELETED":   2,
		"STATE_BLOCKED":   3,
	}
)

func (x CommentState) Enum() *CommentState {
	p := new(CommentState)
	*p = x
	return p
}

func (x CommentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_comment_proto_enumTypes[0].Descriptor()
}

func (CommentState) Type() protoreflect.EnumType {
	return &file_proto_comment_proto_enumTypes[0]
}

func (x CommentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentState.Descriptor instead.
func (CommentState) EnumDescriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{0}
}

// 评论区状态
type SubjectState int32

const (
	SubjectState_SUBJECT_OPEN   SubjectState = 0 //正常
	SubjectState_SUBJECT_CLOSED SubjectState = 1 //评论区关闭
	SubjectState_SUBJECT_ONLY   SubjectState = 2 //仅粉丝可互动
)

// Enum value maps for SubjectState.
var (
	SubjectState_name = map[int32]string{
		0: "SUBJECT_OPEN",
		1: "SUBJECT_CLOSED",
		2: "SUBJECT_ONLY",
	}
	SubjectState_value = map[string]int32{
		"SUBJECT_OPEN":   0,
		"SUBJECT_CLOSED": 1,
		"SUBJECT_ONLY":   2,
	}
)

func (x SubjectState) Enum() *SubjectState {
	p := new(SubjectState)
	*p = x
	return p
}

func (x SubjectState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubjectState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_comment_proto_enumTypes[1].Descriptor()
}

func (SubjectState) Type() protoreflect.EnumType {
	return &file_proto_comment_proto_enumTypes[1]
}

func (x SubjectState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubjectState.Descriptor instead.
func (SubjectState) EnumDescriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{1}
}

type ReportReason int32

const (
	ReportReason_REASON_UNKNOWN ReportReason = 0
	// 垃圾广告
	ReportReason_REASON_SPAM_ADVERT ReportReason = 1
	// 色情低俗
	ReportReason_REASON_PORN_VULGAR ReportReason = 2
	// 人身攻击
	ReportReason_REASON_HARASSMENT_ABUSE ReportReason = 3
	// 违法违规
	ReportReason_REASON_ILLEGAL_COTENT ReportReason = 4
	// 诈骗钓鱼
	ReportReason_REASON_FRAUD_SCAM ReportReason = 5
	// 恶意剧透
	ReportReason_REASON_SPOILER ReportReason = 6
	// 侵犯隐私
	ReportReason_REASON_PRIVACY_LEAK ReportReason = 7
	// 刷屏水军
	ReportReason_REASON_MEANINGLESS_SPAM ReportReason = 8
	// ...预留其他违规类型
	ReportReason_REASON_OTHER ReportReason = 99
)

// Enum value maps for ReportReason.
var (
	ReportReason_name = map[int32]string{
		0:  "REASON_UNKNOWN",
		1:  "REASON_SPAM_ADVERT",
		2:  "REASON_PORN_VULGAR",
		3:  "REASON_HARASSMENT_ABUSE",
		4:  "REASON_ILLEGAL_COTENT",
		5:  "REASON_FRAUD_SCAM",
		6:  "REASON_SPOILER",
		7:  "REASON_PRIVACY_LEAK",
		8:  "REASON_MEANINGLESS_SPAM",
		99: "REASON_OTHER",
	}
	ReportReason_value = map[string]int32{
		"REASON_UNKNOWN":          0,
		"REASON_SPAM_ADVERT":      1,
		"REASON_PORN_VULGAR":      2,
		"REASON_HARASSMENT_ABUSE": 3,
		"REASON_ILLEGAL_COTENT":   4,
		"REASON_FRAUD_SCAM":       5,
		"REASON_SPOILER":          6,
		"REASON_PRIVACY_LEAK":     7,
		"REASON_MEANINGLESS_SPAM": 8,
		"REASON_OTHER":            99,
	}
)

func (x ReportReason) Enum() *ReportReason {
	p := new(ReportReason)
	*p = x
	return p
}

func (x ReportReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_comment_proto_enumTypes[2].Descriptor()
}

func (ReportReason) Type() protoreflect.EnumType {
	return &file_proto_comment_proto_enumTypes[2]
}

func (x ReportReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportReason.Descriptor instead.
func (ReportReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{2}
}

type ManageType int32

const (
	ManageType_UNKNOWN ManageType = 0
	// 置顶
	ManageType_MANAGE_PIN ManageType = 1
	// 取消置顶
	ManageType_MANAGE_UNPIN ManageType = 2
	// 精选
	ManageType_MANAGE_FEATURE ManageType = 3
	// 取消精选
	ManageType_MANAGE_UNFEATURE ManageType = 4
)

// Enum value maps for ManageType.
var (
	ManageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MANAGE_PIN",
		2: "MANAGE_UNPIN",
		3: "MANAGE_FEATURE",
		4: "MANAGE_UNFEATURE",
	}
	ManageType_value = map[string]int32{
		"UNKNOWN":          0,
		"MANAGE_PIN":       1,
		"MANAGE_UNPIN":     2,
		"MANAGE_FEATURE":   3,
		"MANAGE_UNFEATURE": 4,
	}
)

func (x ManageType) Enum() *ManageType {
	p := new(ManageType)
	*p = x
	return p
}

func (x ManageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_comment_proto_enumTypes[3].Descriptor()
}

func (ManageType) Type() protoreflect.EnumType {
	return &file_proto_comment_proto_enumTypes[3]
}

func (x ManageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManageType.Descriptor instead.
func (ManageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{3}
}

type CommentItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 评论Id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 发布者Id
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 评论内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 评论结构部分参考了B站的那篇文章
	// 根评论的id
	RootId int64 `protobuf:"varint,4,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	// 父评论的id
	ParentId int64 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// 点赞数
	LikeCount int64 `protobuf:"varint,6,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	// 点踩数
	DislikeCount int64 `protobuf:"varint,7,opt,name=dislike_count,json=dislikeCount,proto3" json:"dislike_count,omitempty"`
	// 该评论下的评论数
	ReplyCount int64 `protobuf:"varint,8,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	// 该评论的属性,同样参考了B站的设计
	// 用类似bitset的东西来存属性
	// 目前设计的是第0位表示作者赞过,第1位表示作者回复过,第2位表示评论置顶,第3位表示评论精选
	Attribute int64 `protobuf:"varint,9,opt,name=attribute,proto3" json:"attribute,omitempty"`
	// 该评论的状态
	State CommentState `protobuf:"varint,10,opt,name=state,proto3,enum=pb.CommentState" json:"state,omitempty"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 可扩展
	Meta string `protobuf:"bytes,12,opt,name=meta,proto3" json:"meta,omitempty"`
	// 该评论下的2-3条子评论
	Children      []*CommentItem `protobuf:"bytes,13,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentItem) Reset() {
	*x = CommentItem{}
	mi := &file_proto_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentItem) ProtoMessage() {}

func (x *CommentItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentItem.ProtoReflect.Descriptor instead.
func (*CommentItem) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CommentItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentItem) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *CommentItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentItem) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentItem) GetDislikeCount() int64 {
	if x != nil {
		return x.DislikeCount
	}
	return 0
}

func (x *CommentItem) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *CommentItem) GetAttribute() int64 {
	if x != nil {
		return x.Attribute
	}
	return 0
}

func (x *CommentItem) GetState() CommentState {
	if x != nil {
		return x.State
	}
	return CommentState_STATE_NORMAL
}

func (x *CommentItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommentItem) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *CommentItem) GetChildren() []*CommentItem {
	if x != nil {
		return x.Children
	}
	return nil
}

type SubjectInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 该评论区所属内容的类型,包括article,vedio等
	TargetType string `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// 所属内容的ID,例如B站的BV号
	TargetId string `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 总评论数
	TotalCount int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// 总的根评论数
	RootCount int64 `protobuf:"varint,4,opt,name=root_count,json=rootCount,proto3" json:"root_count,omitempty"`
	// 评论区状态
	State SubjectState `protobuf:"varint,5,opt,name=state,proto3,enum=pb.SubjectState" json:"state,omitempty"`
	// 评论区属性,比如第0位为0表示按热度排序,1表示按照时间排序,第1位表示能否附带图片,...
	Attribute     int64 `protobuf:"varint,6,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectInfo) Reset() {
	*x = SubjectInfo{}
	mi := &file_proto_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectInfo) ProtoMessage() {}

func (x *SubjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectInfo.ProtoReflect.Descriptor instead.
func (*SubjectInfo) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{1}
}

func (x *SubjectInfo) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *SubjectInfo) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SubjectInfo) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SubjectInfo) GetRootCount() int64 {
	if x != nil {
		return x.RootCount
	}
	return 0
}

func (x *SubjectInfo) GetState() SubjectState {
	if x != nil {
		return x.State
	}
	return SubjectState_SUBJECT_OPEN
}

func (x *SubjectInfo) GetAttribute() int64 {
	if x != nil {
		return x.Attribute
	}
	return 0
}

type CreateCommentReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 发布者id
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 该评论区所属内容的类型,包括article,vedio等
	TargetType string `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// 所属内容的ID,例如B站的BV号
	TargetId string `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 顶层楼主id
	RootId int64 `protobuf:"varint,4,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	// 回复的评论id
	ParentId int64 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// 评论内容
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// 扩展内容
	Meta          string `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_proto_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCommentReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CreateCommentReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CreateCommentReq) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *CreateCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentReq) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type CreateCommentResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 评论id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 操作后评论区的总评论数
	SubjectCount  int64 `protobuf:"varint,3,opt,name=subject_count,json=subjectCount,proto3" json:"subject_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResp) Reset() {
	*x = CreateCommentResp{}
	mi := &file_proto_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResp) ProtoMessage() {}

func (x *CreateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResp.ProtoReflect.Descriptor instead.
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCommentResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateCommentResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateCommentResp) GetSubjectCount() int64 {
	if x != nil {
		return x.SubjectCount
	}
	return 0
}

type GetCommentReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 所属内容类型
	TargetType string `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// 所属内容id
	TargetId string `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 评论的排序方式,0表示按热度,1表示按时间
	SortType int64 `protobuf:"varint,3,opt,name=sort_type,json=sortType,proto3" json:"sort_type,omitempty"`
	// 根评论id,为0表示查询根评论
	RootId int64 `protobuf:"varint,4,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	// 页码
	Page int64 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	// 每一页大小
	PageSize      int64 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentReq) Reset() {
	*x = GetCommentReq{}
	mi := &file_proto_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentReq) ProtoMessage() {}

func (x *GetCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentReq.ProtoReflect.Descriptor instead.
func (*GetCommentReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommentReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *GetCommentReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GetCommentReq) GetSortType() int64 {
	if x != nil {
		return x.SortType
	}
	return 0
}

func (x *GetCommentReq) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *GetCommentReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCommentResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 评论内容
	Comment []*CommentItem `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	// 评论区
	Subject       *SubjectInfo `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentResp) Reset() {
	*x = GetCommentResp{}
	mi := &file_proto_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentResp) ProtoMessage() {}

func (x *GetCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentResp.ProtoReflect.Descriptor instead.
func (*GetCommentResp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{5}
}

func (x *GetCommentResp) GetComment() []*CommentItem {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *GetCommentResp) GetSubject() *SubjectInfo {
	if x != nil {
		return x.Subject
	}
	return nil
}

type LikeCommentReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 点赞者id
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 评论所属内容类型
	TargetType string `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// 内容id
	TargetId string `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 点赞的评论id
	CommentId int64 `protobuf:"varint,4,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	// 1表示点赞,2表示取消点赞,3表示点踩,4表示取消点踩
	ActionType    int32 `protobuf:"varint,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentReq) Reset() {
	*x = LikeCommentReq{}
	mi := &file_proto_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentReq) ProtoMessage() {}

func (x *LikeCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentReq.ProtoReflect.Descriptor instead.
func (*LikeCommentReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{6}
}

func (x *LikeCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeCommentReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *LikeCommentReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *LikeCommentReq) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *LikeCommentReq) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type LikeCommentResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 操作后的点赞数
	LikeCount     int64 `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentResp) Reset() {
	*x = LikeCommentResp{}
	mi := &file_proto_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResp) ProtoMessage() {}

func (x *LikeCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResp.ProtoReflect.Descriptor instead.
func (*LikeCommentResp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{7}
}

func (x *LikeCommentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LikeCommentResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type DeleteCommentReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作人id,用于检测是否为本人或up主操作防止出现安全问题
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 评论id
	CommentId int64 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	// 同上
	TargetType    string `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_proto_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteCommentReq) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *DeleteCommentReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *DeleteCommentReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type DeleteCommentResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 删除后评论区剩下的评论数
	SubjectTotalCount int64 `protobuf:"varint,2,opt,name=subject_total_count,json=subjectTotalCount,proto3" json:"subject_total_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteCommentResp) Reset() {
	*x = DeleteCommentResp{}
	mi := &file_proto_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResp) ProtoMessage() {}

func (x *DeleteCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResp.ProtoReflect.Descriptor instead.
func (*DeleteCommentResp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCommentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCommentResp) GetSubjectTotalCount() int64 {
	if x != nil {
		return x.SubjectTotalCount
	}
	return 0
}

// 置顶评论
type ManageCommentReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 参数含义同Delete部分
	UserId     int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommentId  int64  `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	TargetType string `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId   string `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 管理类型
	ActionType    ManageType `protobuf:"varint,5,opt,name=action_type,json=actionType,proto3,enum=pb.ManageType" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageCommentReq) Reset() {
	*x = ManageCommentReq{}
	mi := &file_proto_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageCommentReq) ProtoMessage() {}

func (x *ManageCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageCommentReq.ProtoReflect.Descriptor instead.
func (*ManageCommentReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{10}
}

func (x *ManageCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ManageCommentReq) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *ManageCommentReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ManageCommentReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ManageCommentReq) GetActionType() ManageType {
	if x != nil {
		return x.ActionType
	}
	return ManageType_UNKNOWN
}

type ManageCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageCommentResp) Reset() {
	*x = ManageCommentResp{}
	mi := &file_proto_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageCommentResp) ProtoMessage() {}

func (x *ManageCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageCommentResp.ProtoReflect.Descriptor instead.
func (*ManageCommentResp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{11}
}

func (x *ManageCommentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 举报评论
type ReportCommentReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommentId  int64                  `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	TargetType string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId   string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 举报原因
	Reason ReportReason `protobuf:"varint,5,opt,name=reason,proto3,enum=pb.ReportReason" json:"reason,omitempty"`
	// 具体举报内容
	Detail        string `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCommentReq) Reset() {
	*x = ReportCommentReq{}
	mi := &file_proto_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCommentReq) ProtoMessage() {}

func (x *ReportCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCommentReq.ProtoReflect.Descriptor instead.
func (*ReportCommentReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{12}
}

func (x *ReportCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportCommentReq) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *ReportCommentReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ReportCommentReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ReportCommentReq) GetReason() ReportReason {
	if x != nil {
		return x.Reason
	}
	return ReportReason_REASON_UNKNOWN
}

func (x *ReportCommentReq) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ReportCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCommentResp) Reset() {
	*x = ReportCommentResp{}
	mi := &file_proto_comment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCommentResp) ProtoMessage() {}

func (x *ReportCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCommentResp.ProtoReflect.Descriptor instead.
func (*ReportCommentResp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{13}
}

func (x *ReportCommentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateSubjectStateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 只有up主或管理员才有权关闭评论区
	UserId     int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetType string `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId   string `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 目标状态
	State         SubjectState `protobuf:"varint,4,opt,name=state,proto3,enum=pb.SubjectState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubjectStateReq) Reset() {
	*x = UpdateSubjectStateReq{}
	mi := &file_proto_comment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubjectStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubjectStateReq) ProtoMessage() {}

func (x *UpdateSubjectStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubjectStateReq.ProtoReflect.Descriptor instead.
func (*UpdateSubjectStateReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateSubjectStateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateSubjectStateReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *UpdateSubjectStateReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *UpdateSubjectStateReq) GetState() SubjectState {
	if x != nil {
		return x.State
	}
	return SubjectState_SUBJECT_OPEN
}

type UpdateSubjectStateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubjectStateResp) Reset() {
	*x = UpdateSubjectStateResp{}
	mi := &file_proto_comment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubjectStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubjectStateResp) ProtoMessage() {}

func (x *UpdateSubjectStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubjectStateResp.ProtoReflect.Descriptor instead.
func (*UpdateSubjectStateResp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateSubjectStateResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_comment_proto protoreflect.FileDescriptor

const file_proto_comment_proto_rawDesc = "" +
	"\n" +
	"\x13proto/comment.proto\x12\x02pb\"\x91\x03\n" +
	"\vCommentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x17\n" +
	"\aroot_id\x18\x04 \x01(\x03R\x06rootId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12\x1d\n" +
	"\n" +
	"like_count\x18\x06 \x01(\x03R\tlikeCount\x12#\n" +
	"\rdislike_count\x18\a \x01(\x03R\fdislikeCount\x12\x1f\n" +
	"\vreply_count\x18\b \x01(\x03R\n" +
	"replyCount\x12\x1c\n" +
	"\tattribute\x18\t \x01(\x03R\tattribute\x12&\n" +
	"\x05state\x18\n" +
	" \x01(\x0e2\x10.pb.CommentStateR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x12\n" +
	"\x04meta\x18\f \x01(\tR\x04meta\x12+\n" +
	"\bchildren\x18\r \x03(\v2\x0f.pb.CommentItemR\bchildren\"\xd1\x01\n" +
	"\vSubjectInfo\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"root_count\x18\x04 \x01(\x03R\trootCount\x12&\n" +
	"\x05state\x18\x05 \x01(\x0e2\x10.pb.SubjectStateR\x05state\x12\x1c\n" +
	"\tattribute\x18\x06 \x01(\x03R\tattribute\"\xcd\x01\n" +
	"\x10CreateCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x17\n" +
	"\aroot_id\x18\x04 \x01(\x03R\x06rootId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x12\n" +
	"\x04meta\x18\a \x01(\tR\x04meta\"g\n" +
	"\x11CreateCommentResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12#\n" +
	"\rsubject_count\x18\x03 \x01(\x03R\fsubjectCount\"\xb4\x01\n" +
	"\rGetCommentReq\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1b\n" +
	"\tsort_type\x18\x03 \x01(\x03R\bsortType\x12\x17\n" +
	"\aroot_id\x18\x04 \x01(\x03R\x06rootId\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x03R\bpageSize\"f\n" +
	"\x0eGetCommentResp\x12)\n" +
	"\acomment\x18\x01 \x03(\v2\x0f.pb.CommentItemR\acomment\x12)\n" +
	"\asubject\x18\x02 \x01(\v2\x0f.pb.SubjectInfoR\asubject\"\xa7\x01\n" +
	"\x0eLikeCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x04 \x01(\x03R\tcommentId\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\x05R\n" +
	"actionType\"J\n" +
	"\x0fLikeCommentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03R\tlikeCount\"\x88\x01\n" +
	"\x10DeleteCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x03R\tcommentId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\"]\n" +
	"\x11DeleteCommentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x13subject_total_count\x18\x02 \x01(\x03R\x11subjectTotalCount\"\xb9\x01\n" +
	"\x10ManageCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x03R\tcommentId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12/\n" +
	"\vaction_type\x18\x05 \x01(\x0e2\x0e.pb.ManageTypeR\n" +
	"actionType\"-\n" +
	"\x11ManageCommentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xca\x01\n" +
	"\x10ReportCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x03R\tcommentId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12(\n" +
	"\x06reason\x18\x05 \x01(\x0e2\x10.pb.ReportReasonR\x06reason\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\"-\n" +
	"\x11ReportCommentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x96\x01\n" +
	"\x15UpdateSubjectStateReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12&\n" +
	"\x05state\x18\x04 \x01(\x0e2\x10.pb.SubjectStateR\x05state\"2\n" +
	"\x16UpdateSubjectStateResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*[\n" +
	"\fCommentState\x12\x10\n" +
	"\fSTATE_NORMAL\x10\x00\x12\x13\n" +
	"\x0fSTATE_REVIEWING\x10\x01\x12\x11\n" +
	"\rSTATE_DELETED\x10\x02\x12\x11\n" +
	"\rSTATE_BLOCKED\x10\x03*F\n" +
	"\fSubjectState\x12\x10\n" +
	"\fSUBJECT_OPEN\x10\x00\x12\x12\n" +
	"\x0eSUBJECT_CLOSED\x10\x01\x12\x10\n" +
	"\fSUBJECT_ONLY\x10\x02*\xfd\x01\n" +
	"\fReportReason\x12\x12\n" +
	"\x0eREASON_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12REASON_SPAM_ADVERT\x10\x01\x12\x16\n" +
	"\x12REASON_PORN_VULGAR\x10\x02\x12\x1b\n" +
	"\x17REASON_HARASSMENT_ABUSE\x10\x03\x12\x19\n" +
	"\x15REASON_ILLEGAL_COTENT\x10\x04\x12\x15\n" +
	"\x11REASON_FRAUD_SCAM\x10\x05\x12\x12\n" +
	"\x0eREASON_SPOILER\x10\x06\x12\x17\n" +
	"\x13REASON_PRIVACY_LEAK\x10\a\x12\x1b\n" +
	"\x17REASON_MEANINGLESS_SPAM\x10\b\x12\x10\n" +
	"\fREASON_OTHER\x10c*e\n" +
	"\n" +
	"ManageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"MANAGE_PIN\x10\x01\x12\x10\n" +
	"\fMANAGE_UNPIN\x10\x02\x12\x12\n" +
	"\x0eMANAGE_FEATURE\x10\x03\x12\x14\n" +
	"\x10MANAGE_UNFEATURE\x10\x042\xc2\x03\n" +
	"\x0eCommentService\x12<\n" +
	"\rCreateComment\x12\x14.pb.CreateCommentReq\x1a\x15.pb.CreateCommentResp\x123\n" +
	"\n" +
	"GetComment\x12\x11.pb.GetCommentReq\x1a\x12.pb.GetCommentResp\x12<\n" +
	"\rDeleteComment\x12\x14.pb.DeleteCommentReq\x1a\x15.pb.DeleteCommentResp\x126\n" +
	"\vLikeComment\x12\x12.pb.LikeCommentReq\x1a\x13.pb.LikeCommentResp\x12<\n" +
	"\rReportComment\x12\x14.pb.ReportCommentReq\x1a\x15.pb.ReportCommentResp\x12<\n" +
	"\rManageComment\x12\x14.pb.ManageCommentReq\x1a\x15.pb.ManageCommentResp\x12K\n" +
	"\x12UpdateSubjectState\x12\x19.pb.UpdateSubjectStateReq\x1a\x1a.pb.UpdateSubjectStateRespB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_comment_proto_rawDescOnce sync.Once
	file_proto_comment_proto_rawDescData []byte
)

func file_proto_comment_proto_rawDescGZIP() []byte {
	file_proto_comment_proto_rawDescOnce.Do(func() {
		file_proto_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_comment_proto_rawDesc), len(file_proto_comment_proto_rawDesc)))
	})
	return file_proto_comment_proto_rawDescData
}

var file_proto_comment_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_comment_proto_goTypes = []any{
	(CommentState)(0),              // 0: pb.CommentState
	(SubjectState)(0),              // 1: pb.SubjectState
	(ReportReason)(0),              // 2: pb.ReportReason
	(ManageType)(0),                // 3: pb.ManageType
	(*CommentItem)(nil),            // 4: pb.CommentItem
	(*SubjectInfo)(nil),            // 5: pb.SubjectInfo
	(*CreateCommentReq)(nil),       // 6: pb.CreateCommentReq
	(*CreateCommentResp)(nil),      // 7: pb.CreateCommentResp
	(*GetCommentReq)(nil),          // 8: pb.GetCommentReq
	(*GetCommentResp)(nil),         // 9: pb.GetCommentResp
	(*LikeCommentReq)(nil),         // 10: pb.LikeCommentReq
	(*LikeCommentResp)(nil),        // 11: pb.LikeCommentResp
	(*DeleteCommentReq)(nil),       // 12: pb.DeleteCommentReq
	(*DeleteCommentResp)(nil),      // 13: pb.DeleteCommentResp
	(*ManageCommentReq)(nil),       // 14: pb.ManageCommentReq
	(*ManageCommentResp)(nil),      // 15: pb.ManageCommentResp
	(*ReportCommentReq)(nil),       // 16: pb.ReportCommentReq
	(*ReportCommentResp)(nil),      // 17: pb.ReportCommentResp
	(*UpdateSubjectStateReq)(nil),  // 18: pb.UpdateSubjectStateReq
	(*UpdateSubjectStateResp)(nil), // 19: pb.UpdateSubjectStateResp
}
var file_proto_comment_proto_depIdxs = []int32{
	0,  // 0: pb.CommentItem.state:type_name -> pb.CommentState
	4,  // 1: pb.CommentItem.children:type_name -> pb.CommentItem
	1,  // 2: pb.SubjectInfo.state:type_name -> pb.SubjectState
	4,  // 3: pb.GetCommentResp.comment:type_name -> pb.CommentItem
	5,  // 4: pb.GetCommentResp.subject:type_name -> pb.SubjectInfo
	3,  // 5: pb.ManageCommentReq.action_type:type_name -> pb.ManageType
	2,  // 6: pb.ReportCommentReq.reason:type_name -> pb.ReportReason
	1,  // 7: pb.UpdateSubjectStateReq.state:type_name -> pb.SubjectState
	6,  // 8: pb.CommentService.CreateComment:input_type -> pb.CreateCommentReq
	8,  // 9: pb.CommentService.GetComment:input_type -> pb.GetCommentReq
	12, // 10: pb.CommentService.DeleteComment:input_type -> pb.DeleteCommentReq
	10, // 11: pb.CommentService.LikeComment:input_type -> pb.LikeCommentReq
	16, // 12: pb.CommentService.ReportComment:input_type -> pb.ReportCommentReq
	14, // 13: pb.CommentService.ManageComment:input_type -> pb.ManageCommentReq
	18, // 14: pb.CommentService.UpdateSubjectState:input_type -> pb.UpdateSubjectStateReq
	7,  // 15: pb.CommentService.CreateComment:output_type -> pb.CreateCommentResp
	9,  // 16: pb.CommentService.GetComment:output_type -> pb.GetCommentResp
	13, // 17: pb.CommentService.DeleteComment:output_type -> pb.DeleteCommentResp
	11, // 18: pb.CommentService.LikeComment:output_type -> pb.LikeCommentResp
	17, // 19: pb.CommentService.ReportComment:output_type -> pb.ReportCommentResp
	15, // 20: pb.CommentService.ManageComment:output_type -> pb.ManageCommentResp
	19, // 21: pb.CommentService.UpdateSubjectState:output_type -> pb.UpdateSubjectStateResp
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_comment_proto_init() }
func file_proto_comment_proto_init() {
	if File_proto_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_comment_proto_rawDesc), len(file_proto_comment_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_comment_proto_goTypes,
		DependencyIndexes: file_proto_comment_proto_depIdxs,
		EnumInfos:         file_proto_comment_proto_enumTypes,
		MessageInfos:      file_proto_comment_proto_msgTypes,
	}.Build()
	File_proto_comment_proto = out.File
	file_proto_comment_proto_goTypes = nil
	file_proto_comment_proto_depIdxs = nil
}
