// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package server

import (
	"context"

	"sea-try-go/service/comment/internal/logic"
	"sea-try-go/service/comment/internal/svc"
	"sea-try-go/service/comment/pb"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServiceServer) CreateComment(ctx context.Context, in *pb.CreateCommentReq) (*pb.CreateCommentResp, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *CommentServiceServer) GetComment(ctx context.Context, in *pb.GetCommentReq) (*pb.GetCommentResp, error) {
	l := logic.NewGetCommentLogic(ctx, s.svcCtx)
	return l.GetComment(in)
}

func (s *CommentServiceServer) DeleteComment(ctx context.Context, in *pb.DeleteCommentReq) (*pb.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *CommentServiceServer) LikeComment(ctx context.Context, in *pb.LikeCommentReq) (*pb.LikeCommentResp, error) {
	l := logic.NewLikeCommentLogic(ctx, s.svcCtx)
	return l.LikeComment(in)
}

func (s *CommentServiceServer) ReportComment(ctx context.Context, in *pb.ReportCommentReq) (*pb.ReportCommentResp, error) {
	l := logic.NewReportCommentLogic(ctx, s.svcCtx)
	return l.ReportComment(in)
}

func (s *CommentServiceServer) ManageComment(ctx context.Context, in *pb.ManageCommentReq) (*pb.ManageCommentResp, error) {
	l := logic.NewManageCommentLogic(ctx, s.svcCtx)
	return l.ManageComment(in)
}

func (s *CommentServiceServer) UpdateSubjectState(ctx context.Context, in *pb.UpdateSubjectStateReq) (*pb.UpdateSubjectStateResp, error) {
	l := logic.NewUpdateSubjectStateLogic(ctx, s.svcCtx)
	return l.UpdateSubjectState(in)
}
