// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	folder "favorite-system/api/internal/handler/folder"
	item "favorite-system/api/internal/handler/item"
	"favorite-system/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/folder/create",
				Handler: folder.CreateFolderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/folder/delete",
				Handler: folder.DeleteFolderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/folder/detail",
				Handler: folder.GetFolderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/folder/list",
				Handler: folder.ListFoldersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/folder/update",
				Handler: folder.UpdateFolderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/favorite"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/item/add",
				Handler: item.AddFavoriteItemHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/item/check",
				Handler: item.CheckFavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/item/list",
				Handler: item.ListFavoriteItemsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/item/remove",
				Handler: item.RemoveFavoriteItemHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/favorite"),
	)
}
