// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateFolderReq struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	IsPublic    bool   `json:"is_public"`
}

type CreateFolderResp struct {
	Id int64 `json:"id,string"`
}

type FolderInfo struct {
	Id          int64  `json:"id,string"`
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	IsPublic    bool   `json:"is_public"`
	CreatedAt   string `json:"created_at"`
}

type ListFolderReq struct {
}

type ListFolderResp struct {
	List []FolderInfo `json:"list"`
}

// User types
type UserInfo struct {
	Uid       int64             `json:"uid,string"`
	Score     uint32            `json:"score"`
	Username  string            `json:"username"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type GetUserReq struct {
}

type GetUserResp struct {
	User  UserInfo `json:"user,omitempty"`
	Found bool     `json:"found"`
}

type CreateUserReq struct {
	Username  string            `json:"username"`
	Password  string            `json:"password"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type CreateUserResp struct {
	Uid int64 `json:"uid,string"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type LogoutReq struct {
}

type LogoutResp struct {
	Success bool `json:"success"`
}

type UpdateUserReq struct {
	Username  string            `json:"username,omitempty"`
	Password  string            `json:"password,omitempty"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type UpdateUserResp struct {
	User UserInfo `json:"user"`
}

type DeleteUserReq struct {
}

type DeleteUserResp struct {
	Success bool `json:"success"`
}
