// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddFavoriteItemReq struct {
	FolderId   int64  `json:"folder_id,string"`
	ObjectType string `json:"object_type"` // article, video, etc.
	ObjectId   int64  `json:"object_id,string"`
	Title      string `json:"title"` // 快照标题
}

type BaseResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type CheckFavoriteReq struct {
	ObjectType string `form:"object_type"`
	ObjectId   int64  `form:"object_id,string"`
}

type CheckFavoriteResp struct {
	IsFavorited bool  `json:"is_favorited"`
	FolderId    int64 `json:"folder_id,string"` // If favorited, return folder id
}

type CreateFolderReq struct {
	Name     string `json:"name"`
	IsPublic bool   `json:"is_public"`
}

type CreateFolderResp struct {
	Id int64 `json:"id,string"`
}

type DeleteFolderReq struct {
	Id int64 `json:"id,string"`
}

type FavoriteItemInfo struct {
	Id         int64  `json:"id,string"`
	FolderId   int64  `json:"folder_id,string"`
	UserId     int64  `json:"user_id,string"`
	ObjectType string `json:"object_type"`
	ObjectId   int64  `json:"object_id,string"`
	Title      string `json:"title"`
	CreatedAt  int64  `json:"created_at"`
}

type FolderInfo struct {
	Id        int64  `json:"id,string"`
	UserId    int64  `json:"user_id,string"`
	Name      string `json:"name"`
	IsPublic  bool   `json:"is_public"`
	CreatedAt int64  `json:"created_at"`
}

type GetFolderReq struct {
	FolderId int64 `form:"folder_id,string"`
}

type GetFolderResp struct {
	Folder FolderInfo `json:"folder"`
}

type ListFavoriteItemsReq struct {
	FolderId int64 `form:"folder_id,string"`
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type ListFavoriteItemsResp struct {
	Items    []FavoriteItemInfo `json:"items"`
	Total    int64              `json:"total"`
	Page     int32              `json:"page"`
	PageSize int32              `json:"page_size"`
}

type ListFoldersReq struct {
	UserId int64 `form:"user_id,string"` // 查询指定用户的收藏夹
}

type ListFoldersResp struct {
	Folders []FolderInfo `json:"folders"`
}

type RemoveFavoriteItemReq struct {
	FolderId   int64  `json:"folder_id,string"`
	ObjectType string `json:"object_type"`
	ObjectId   int64  `json:"object_id,string"`
}

type UpdateFolderReq struct {
	Id       int64  `json:"id,string"`
	Name     string `json:"name"`
	IsPublic bool   `json:"is_public"`
}
