// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: task.proto

package taskservice

import (
	"context"

	"sea-try-go/service/task/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetTaskReq  = __.GetTaskReq
	GetTaskResp = __.GetTaskResp
	Task        = __.Task

	TaskService interface {
		GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*GetTaskResp, error)
	}

	defaultTaskService struct {
		cli zrpc.Client
	}
)

func NewTaskService(cli zrpc.Client) TaskService {
	return &defaultTaskService{
		cli: cli,
	}
}

func (m *defaultTaskService) GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*GetTaskResp, error) {
	client := __.NewTaskServiceClient(m.cli.Conn())
	return client.GetTask(ctx, in, opts...)
}
