// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	favorite "sea-try-go/api/internal/handler/favorite"
	"sea-try-go/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			// =========== 收藏夹相关 ===========
			{
				// 创建收藏夹
				Method:  http.MethodPost,
				Path:    "/folders",
				Handler: favorite.CreateFolderHandler(serverCtx),
			},
			{
				// 获取收藏夹列表
				Method:  http.MethodGet,
				Path:    "/folders",
				Handler: favorite.ListFolderHandler(serverCtx),
			},

			// =========== 收藏项相关 ===========
			{
				// 添加收藏（到某个收藏夹）
				Method:  http.MethodPost,
				Path:    "/items",
				Handler: favorite.CreateFavoriteHandler(serverCtx),
			},
			{
				// 删除收藏
				Method:  http.MethodDelete,
				Path:    "/items",
				Handler: favorite.DeleteFavoriteHandler(serverCtx),
			},
			{
				// 列表收藏项
				Method:  http.MethodGet,
				Path:    "/items",
				Handler: favorite.ListFavoriteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.UserAuth.AccessSecret),
		rest.WithPrefix("/favorite/v1"),
	)
}
