// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"favorite-system/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/folder/article/add",
				Handler: addArticleToFolderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/folder/article/list",
				Handler: listArticlesInFolderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/folder/article/remove",
				Handler: removeArticleFromFolderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/folder/create",
				Handler: createFolderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/folder/delete",
				Handler: deleteFolderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/folder/list",
				Handler: listFoldersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/folder/update",
				Handler: updateFolderHandler(serverCtx),
			},
		},
	)
}
