// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddArticleReq struct {
	FolderId   int64  `json:"folder_id,string"`
	UserId     int64  `json:"user_id,string"`
	ObjectType string `json:"object_type"`
	ObjectId   int64  `json:"object_id,string"`
	Title      string `json:"title"`
}

type Article struct {
	Id         int64  `json:"id,string"`
	ObjectType string `json:"object_type"`
	ObjectId   int64  `json:"object_id,string"`
	Title      string `json:"title"`
}

type BaseResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type CreateFolderReq struct {
	UserId   int64  `json:"user_id,string"`
	Name     string `json:"name"`
	IsPublic bool   `json:"is_public"`
}

type CreateFolderResp struct {
	Id int64 `json:"id,string"`
}

type DeleteFolderReq struct {
	Id int64 `json:"id,string"`
}

type Folder struct {
	Id       int64  `json:"id,string"`
	UserId   int64  `json:"user_id,string"`
	Name     string `json:"name"`
	IsPublic bool   `json:"is_public"`
	Deleted  bool   `json:"deleted"`
}

type ListArticlesReq struct {
	FolderId int64 `json:"folder_id,string"`
}

type ListArticlesResp struct {
	Articles []Article `json:"articles"`
}

type ListFoldersReq struct {
	UserId int64 `json:"user_id,string"`
}

type ListFoldersResp struct {
	Folders []Folder `json:"folders"`
}

type RemoveArticleReq struct {
	FolderId   int64  `json:"folder_id,string"`
	UserId     int64  `json:"user_id,string"`
	ObjectType string `json:"object_type"`
	ObjectId   int64  `json:"object_id,string"`
}

type UpdateFolderReq struct {
	Id       int64  `json:"id,string"`
	Name     string `json:"name"`
	IsPublic bool   `json:"is_public"`
}
