// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: like.proto

package server

import (
	"context"

	"sea-try-go/service/like/internal/logic"
	"sea-try-go/service/like/internal/svc"
	"sea-try-go/service/like/pb"
)

type LikeServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLikeServiceServer
}

func NewLikeServiceServer(svcCtx *svc.ServiceContext) *LikeServiceServer {
	return &LikeServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServiceServer) LikeAction(ctx context.Context, in *pb.LikeActionReq) (*pb.LikeActionResp, error) {
	l := logic.NewLikeActionLogic(ctx, s.svcCtx)
	return l.LikeAction(in)
}

func (s *LikeServiceServer) GetLikeCount(ctx context.Context, in *pb.GetLikeCountReq) (*pb.GetLikeCountResp, error) {
	l := logic.NewGetLikeCountLogic(ctx, s.svcCtx)
	return l.GetLikeCount(in)
}

func (s *LikeServiceServer) GetLikeState(ctx context.Context, in *pb.GetLikeStateReq) (*pb.GetLikeStateResp, error) {
	l := logic.NewGetLikeStateLogic(ctx, s.svcCtx)
	return l.GetLikeState(in)
}

func (s *LikeServiceServer) GetUserLikeList(ctx context.Context, in *pb.GetUserLikeListReq) (*pb.GetUserLikeListResp, error) {
	l := logic.NewGetUserLikeListLogic(ctx, s.svcCtx)
	return l.GetUserLikeList(in)
}

func (s *LikeServiceServer) GetTargetLikerList(ctx context.Context, in *pb.GetTargetLikerListReq) (*pb.GetTargetLikerListResp, error) {
	l := logic.NewGetTargetLikerListLogic(ctx, s.svcCtx)
	return l.GetTargetLikerList(in)
}

func (s *LikeServiceServer) GetUserTotalLike(ctx context.Context, in *pb.GetUserTotalLikeReq) (*pb.GetUserTotalLikeResp, error) {
	l := logic.NewGetUserTotalLikeLogic(ctx, s.svcCtx)
	return l.GetUserTotalLike(in)
}
