// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: article.proto

package articleservice

import (
	"context"

	"sea-try-go/service/article/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Article               = __.Article
	CreateArticleRequest  = __.CreateArticleRequest
	CreateArticleResponse = __.CreateArticleResponse
	DeleteArticleRequest  = __.DeleteArticleRequest
	DeleteArticleResponse = __.DeleteArticleResponse
	GetArticleRequest     = __.GetArticleRequest
	GetArticleResponse    = __.GetArticleResponse
	LikeArticleRequest    = __.LikeArticleRequest
	LikeArticleResponse   = __.LikeArticleResponse
	ListArticlesRequest   = __.ListArticlesRequest
	ListArticlesResponse  = __.ListArticlesResponse
	UpdateArticleRequest  = __.UpdateArticleRequest
	UpdateArticleResponse = __.UpdateArticleResponse

	ArticleService interface {
		CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*CreateArticleResponse, error)
		GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error)
		UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error)
		DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error)
		ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
		LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error)
	}

	defaultArticleService struct {
		cli zrpc.Client
	}
)

func NewArticleService(cli zrpc.Client) ArticleService {
	return &defaultArticleService{
		cli: cli,
	}
}

func (m *defaultArticleService) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*CreateArticleResponse, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.CreateArticle(ctx, in, opts...)
}

func (m *defaultArticleService) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

func (m *defaultArticleService) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

func (m *defaultArticleService) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}

func (m *defaultArticleService) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.ListArticles(ctx, in, opts...)
}

func (m *defaultArticleService) LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.LikeArticle(ctx, in, opts...)
}
