// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: article.proto

package articleservice

import (
	"context"

	"sea-try-go/service/article/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Article           = __.Article
	CreateArticleReq  = __.CreateArticleReq
	CreateArticleResp = __.CreateArticleResp
	DeleteArticleReq  = __.DeleteArticleReq
	DeleteArticleResp = __.DeleteArticleResp
	GetArticleReq     = __.GetArticleReq
	GetArticleResp    = __.GetArticleResp
	LikeArticleReq    = __.LikeArticleReq
	LikeArticleResp   = __.LikeArticleResp
	ListArticlesReq   = __.ListArticlesReq
	ListArticlesResp  = __.ListArticlesResp
	UpdateArticleReq  = __.UpdateArticleReq
	UpdateArticleResp = __.UpdateArticleResp

	ArticleService interface {
		CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error)
		GetArticle(ctx context.Context, in *GetArticleReq, opts ...grpc.CallOption) (*GetArticleResp, error)
		UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error)
		DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error)
		ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error)
		LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error)
	}

	defaultArticleService struct {
		cli zrpc.Client
	}
)

func NewArticleService(cli zrpc.Client) ArticleService {
	return &defaultArticleService{
		cli: cli,
	}
}

func (m *defaultArticleService) CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.CreateArticle(ctx, in, opts...)
}

func (m *defaultArticleService) GetArticle(ctx context.Context, in *GetArticleReq, opts ...grpc.CallOption) (*GetArticleResp, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

func (m *defaultArticleService) UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

func (m *defaultArticleService) DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}

func (m *defaultArticleService) ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.ListArticles(ctx, in, opts...)
}

func (m *defaultArticleService) LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.LikeArticle(ctx, in, opts...)
}
