// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/hotspot.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//////////////////// hotspot / like /////////////////////
type LikeArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID (?)
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                           // 1=点赞, 2=取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleReq) Reset() {
	*x = LikeArticleReq{}
	mi := &file_proto_hotspot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleReq) ProtoMessage() {}

func (x *LikeArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotspot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleReq.ProtoReflect.Descriptor instead.
func (*LikeArticleReq) Descriptor() ([]byte, []int) {
	return file_proto_hotspot_proto_rawDescGZIP(), []int{0}
}

func (x *LikeArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *LikeArticleReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LikeArticleReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type LikeArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int32                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"` // 点赞数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleResp) Reset() {
	*x = LikeArticleResp{}
	mi := &file_proto_hotspot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleResp) ProtoMessage() {}

func (x *LikeArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotspot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleResp.ProtoReflect.Descriptor instead.
func (*LikeArticleResp) Descriptor() ([]byte, []int) {
	return file_proto_hotspot_proto_rawDescGZIP(), []int{1}
}

func (x *LikeArticleResp) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

var File_proto_hotspot_proto protoreflect.FileDescriptor

const file_proto_hotspot_proto_rawDesc = "" +
	"\n" +
	"\x13proto/hotspot.proto\x12\ahotspot\"\\\n" +
	"\x0eLikeArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\"0\n" +
	"\x0fLikeArticleResp\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x05R\tlikeCount2R\n" +
	"\x0eArticleService\x12@\n" +
	"\vLikeArticle\x12\x17.hotspot.LikeArticleReq\x1a\x18.hotspot.LikeArticleRespB\x03Z\x01.b\x06proto3"

var (
	file_proto_hotspot_proto_rawDescOnce sync.Once
	file_proto_hotspot_proto_rawDescData []byte
)

func file_proto_hotspot_proto_rawDescGZIP() []byte {
	file_proto_hotspot_proto_rawDescOnce.Do(func() {
		file_proto_hotspot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hotspot_proto_rawDesc), len(file_proto_hotspot_proto_rawDesc)))
	})
	return file_proto_hotspot_proto_rawDescData
}

var file_proto_hotspot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hotspot_proto_goTypes = []any{
	(*LikeArticleReq)(nil),  // 0: hotspot.LikeArticleReq
	(*LikeArticleResp)(nil), // 1: hotspot.LikeArticleResp
}
var file_proto_hotspot_proto_depIdxs = []int32{
	0, // 0: hotspot.ArticleService.LikeArticle:input_type -> hotspot.LikeArticleReq
	1, // 1: hotspot.ArticleService.LikeArticle:output_type -> hotspot.LikeArticleResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hotspot_proto_init() }
func file_proto_hotspot_proto_init() {
	if File_proto_hotspot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hotspot_proto_rawDesc), len(file_proto_hotspot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hotspot_proto_goTypes,
		DependencyIndexes: file_proto_hotspot_proto_depIdxs,
		MessageInfos:      file_proto_hotspot_proto_msgTypes,
	}.Build()
	File_proto_hotspot_proto = out.File
	file_proto_hotspot_proto_goTypes = nil
	file_proto_hotspot_proto_depIdxs = nil
}
