// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorite_items.sql

package db

import (
	"context"
)

const addFavoriteItem = `-- name: AddFavoriteItem :one
INSERT INTO favorite_items (folder_id, user_id, object_type, object_id, title)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, folder_id, user_id, object_type, object_id, title, created_at, updated_at, deleted_at
`

type AddFavoriteItemParams struct {
	FolderID   int64  `json:"folder_id"`
	UserID     int64  `json:"user_id"`
	ObjectType string `json:"object_type"`
	ObjectID   int64  `json:"object_id"`
	Title      string `json:"title"`
}

func (q *Queries) AddFavoriteItem(ctx context.Context, arg AddFavoriteItemParams) (FavoriteItem, error) {
	row := q.db.QueryRow(ctx, addFavoriteItem,
		arg.FolderID,
		arg.UserID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Title,
	)
	var i FavoriteItem
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.UserID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countFavoriteItems = `-- name: CountFavoriteItems :one
SELECT COUNT(*) FROM favorite_items
WHERE folder_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountFavoriteItems(ctx context.Context, folderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoriteItems, folderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFavoriteItem = `-- name: GetFavoriteItem :one
SELECT id, folder_id, user_id, object_type, object_id, title, created_at, updated_at, deleted_at FROM favorite_items
WHERE user_id = $1 AND object_type = $2 AND object_id = $3 AND deleted_at IS NULL
`

type GetFavoriteItemParams struct {
	UserID     int64  `json:"user_id"`
	ObjectType string `json:"object_type"`
	ObjectID   int64  `json:"object_id"`
}

func (q *Queries) GetFavoriteItem(ctx context.Context, arg GetFavoriteItemParams) (FavoriteItem, error) {
	row := q.db.QueryRow(ctx, getFavoriteItem, arg.UserID, arg.ObjectType, arg.ObjectID)
	var i FavoriteItem
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.UserID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllFavoriteItems = `-- name: ListAllFavoriteItems :many
SELECT id, folder_id, user_id, object_type, object_id, title, created_at, updated_at, deleted_at FROM favorite_items
WHERE folder_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAllFavoriteItems(ctx context.Context, folderID int64) ([]FavoriteItem, error) {
	rows, err := q.db.Query(ctx, listAllFavoriteItems, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FavoriteItem
	for rows.Next() {
		var i FavoriteItem
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.UserID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteItems = `-- name: ListFavoriteItems :many
SELECT id, folder_id, user_id, object_type, object_id, title, created_at, updated_at, deleted_at FROM favorite_items
WHERE folder_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFavoriteItemsParams struct {
	FolderID int64 `json:"folder_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListFavoriteItems(ctx context.Context, arg ListFavoriteItemsParams) ([]FavoriteItem, error) {
	rows, err := q.db.Query(ctx, listFavoriteItems, arg.FolderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FavoriteItem
	for rows.Next() {
		var i FavoriteItem
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.UserID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFavoriteItem = `-- name: SoftDeleteFavoriteItem :exec
UPDATE favorite_items
SET deleted_at = NOW()
WHERE folder_id = $1 AND user_id = $2 AND object_type = $3 AND object_id = $4 AND deleted_at IS NULL
`

type SoftDeleteFavoriteItemParams struct {
	FolderID   int64  `json:"folder_id"`
	UserID     int64  `json:"user_id"`
	ObjectType string `json:"object_type"`
	ObjectID   int64  `json:"object_id"`
}

func (q *Queries) SoftDeleteFavoriteItem(ctx context.Context, arg SoftDeleteFavoriteItemParams) error {
	_, err := q.db.Exec(ctx, softDeleteFavoriteItem,
		arg.FolderID,
		arg.UserID,
		arg.ObjectType,
		arg.ObjectID,
	)
	return err
}

const softDeleteFavoriteItemsByFolder = `-- name: SoftDeleteFavoriteItemsByFolder :exec
UPDATE favorite_items
SET deleted_at = NOW()
WHERE folder_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFavoriteItemsByFolder(ctx context.Context, folderID int64) error {
	_, err := q.db.Exec(ctx, softDeleteFavoriteItemsByFolder, folderID)
	return err
}
