// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package db

import (
	"context"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (user_id, name, is_public)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, is_public, created_at, updated_at, deleted_at
`

type CreateFolderParams struct {
	UserID   int64  `json:"user_id"`
	Name     string `json:"name"`
	IsPublic bool   `json:"is_public"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.UserID, arg.Name, arg.IsPublic)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, user_id, name, is_public, created_at, updated_at, deleted_at
FROM folders
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetFolderByID(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFoldersByUser = `-- name: ListFoldersByUser :many
SELECT id, user_id, name, is_public, created_at, updated_at, deleted_at
FROM folders
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListFoldersByUser(ctx context.Context, userID int64) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFolder = `-- name: SoftDeleteFolder :exec
UPDATE folders
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFolder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteFolder, id)
	return err
}

const updateFolder = `-- name: UpdateFolder :exec
UPDATE folders
SET name = $2, is_public = $3, updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateFolderParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	IsPublic bool   `json:"is_public"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) error {
	_, err := q.db.Exec(ctx, updateFolder, arg.ID, arg.Name, arg.IsPublic)
	return err
}
