// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/points.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PointsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointsReq) Reset() {
	*x = PointsReq{}
	mi := &file_proto_points_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsReq) ProtoMessage() {}

func (x *PointsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsReq.ProtoReflect.Descriptor instead.
func (*PointsReq) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{0}
}

func (x *PointsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PointsReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PointsReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type PointsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointsResp) Reset() {
	*x = PointsResp{}
	mi := &file_proto_points_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsResp) ProtoMessage() {}

func (x *PointsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsResp.ProtoReflect.Descriptor instead.
func (*PointsResp) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{1}
}

func (x *PointsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PointsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_points_proto protoreflect.FileDescriptor

const file_proto_points_proto_rawDesc = "" +
	"\n" +
	"\x12proto/points.proto\x12\x06points\"[\n" +
	"\tPointsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"@\n" +
	"\n" +
	"PointsResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2@\n" +
	"\rPointsService\x12/\n" +
	"\x06Points\x12\x11.points.PointsReq\x1a\x12.points.PointsRespB\x03Z\x01.b\x06proto3"

var (
	file_proto_points_proto_rawDescOnce sync.Once
	file_proto_points_proto_rawDescData []byte
)

func file_proto_points_proto_rawDescGZIP() []byte {
	file_proto_points_proto_rawDescOnce.Do(func() {
		file_proto_points_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_points_proto_rawDesc), len(file_proto_points_proto_rawDesc)))
	})
	return file_proto_points_proto_rawDescData
}

var file_proto_points_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_points_proto_goTypes = []any{
	(*PointsReq)(nil),  // 0: points.PointsReq
	(*PointsResp)(nil), // 1: points.PointsResp
}
var file_proto_points_proto_depIdxs = []int32{
	0, // 0: points.PointsService.Points:input_type -> points.PointsReq
	1, // 1: points.PointsService.Points:output_type -> points.PointsResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_points_proto_init() }
func file_proto_points_proto_init() {
	if File_proto_points_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_points_proto_rawDesc), len(file_proto_points_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_points_proto_goTypes,
		DependencyIndexes: file_proto_points_proto_depIdxs,
		MessageInfos:      file_proto_points_proto_msgTypes,
	}.Build()
	File_proto_points_proto = out.File
	file_proto_points_proto_goTypes = nil
	file_proto_points_proto_depIdxs = nil
}
