// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: follow.proto

package followservice

import (
	"context"

	"sea-try-go/service/follow/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResp                    = pb.BaseResp
	ListReq                     = pb.ListReq
	RecommendResp               = pb.RecommendResp
	RecommendResp_RecommendUser = pb.RecommendResp_RecommendUser
	RelationReq                 = pb.RelationReq
	UserListResp                = pb.UserListResp

	FollowService interface {
		// 1. 点击关注 (O(1) 插入边)
		Follow(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error)
		// 2. 取消关注 (O(1) 删除边)
		Unfollow(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error)
		// 3. 拉入黑名单 (O(1) 插入边并清理双向 Follow 边)
		Block(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error)
		// 4. 拉出黑名单 (O(1) 删除边)
		Unblock(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error)
		// 5. 获取关注列表 (O(K), K 为 limit)
		GetFollowList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error)
		// 6. 获取黑名单列表 (O(K))
		GetBlockList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error)
		// 7. 获取粉丝列表 (O(K))
		GetFollowerList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error)
		// 8. 遍历三层关系查找可能喜欢 (受限 BFS)
		GetRecommendations(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*RecommendResp, error)
	}

	defaultFollowService struct {
		cli zrpc.Client
	}
)

func NewFollowService(cli zrpc.Client) FollowService {
	return &defaultFollowService{
		cli: cli,
	}
}

// 1. 点击关注 (O(1) 插入边)
func (m *defaultFollowService) Follow(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

// 2. 取消关注 (O(1) 删除边)
func (m *defaultFollowService) Unfollow(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.Unfollow(ctx, in, opts...)
}

// 3. 拉入黑名单 (O(1) 插入边并清理双向 Follow 边)
func (m *defaultFollowService) Block(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.Block(ctx, in, opts...)
}

// 4. 拉出黑名单 (O(1) 删除边)
func (m *defaultFollowService) Unblock(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.Unblock(ctx, in, opts...)
}

// 5. 获取关注列表 (O(K), K 为 limit)
func (m *defaultFollowService) GetFollowList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.GetFollowList(ctx, in, opts...)
}

// 6. 获取黑名单列表 (O(K))
func (m *defaultFollowService) GetBlockList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.GetBlockList(ctx, in, opts...)
}

// 7. 获取粉丝列表 (O(K))
func (m *defaultFollowService) GetFollowerList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.GetFollowerList(ctx, in, opts...)
}

// 8. 遍历三层关系查找可能喜欢 (受限 BFS)
func (m *defaultFollowService) GetRecommendations(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*RecommendResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.GetRecommendations(ctx, in, opts...)
}
