// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package server

import (
	"context"
	logic2 "sea-try-go/service/comment/rpc/internal/logic"
	"sea-try-go/service/comment/rpc/internal/svc"
	pb2 "sea-try-go/service/comment/rpc/pb"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	pb2.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServiceServer) CreateComment(ctx context.Context, in *pb2.CreateCommentReq) (*pb2.CreateCommentResp, error) {
	l := logic2.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *CommentServiceServer) GetComment(ctx context.Context, in *pb2.GetCommentReq) (*pb2.GetCommentResp, error) {
	l := logic2.NewGetCommentLogic(ctx, s.svcCtx)
	return l.GetComment(in)
}

func (s *CommentServiceServer) DeleteComment(ctx context.Context, in *pb2.DeleteCommentReq) (*pb2.DeleteCommentResp, error) {
	l := logic2.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *CommentServiceServer) LikeComment(ctx context.Context, in *pb2.LikeCommentReq) (*pb2.LikeCommentResp, error) {
	l := logic2.NewLikeCommentLogic(ctx, s.svcCtx)
	return l.LikeComment(in)
}

func (s *CommentServiceServer) ReportComment(ctx context.Context, in *pb2.ReportCommentReq) (*pb2.ReportCommentResp, error) {
	l := logic2.NewReportCommentLogic(ctx, s.svcCtx)
	return l.ReportComment(in)
}

func (s *CommentServiceServer) ManageComment(ctx context.Context, in *pb2.ManageCommentReq) (*pb2.ManageCommentResp, error) {
	l := logic2.NewManageCommentLogic(ctx, s.svcCtx)
	return l.ManageComment(in)
}

func (s *CommentServiceServer) UpdateSubjectState(ctx context.Context, in *pb2.UpdateSubjectStateReq) (*pb2.UpdateSubjectStateResp, error) {
	l := logic2.NewUpdateSubjectStateLogic(ctx, s.svcCtx)
	return l.UpdateSubjectState(in)
}
