// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: content_security.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentSecurityService_SanitizeContent_FullMethodName = "/content_security.ContentSecurityService/SanitizeContent"
)

// ContentSecurityServiceClient is the client API for ContentSecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentSecurityServiceClient interface {
	SanitizeContent(ctx context.Context, in *SanitizeContentRequest, opts ...grpc.CallOption) (*SanitizeContentResponse, error)
}

type contentSecurityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentSecurityServiceClient(cc grpc.ClientConnInterface) ContentSecurityServiceClient {
	return &contentSecurityServiceClient{cc}
}

func (c *contentSecurityServiceClient) SanitizeContent(ctx context.Context, in *SanitizeContentRequest, opts ...grpc.CallOption) (*SanitizeContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SanitizeContentResponse)
	err := c.cc.Invoke(ctx, ContentSecurityService_SanitizeContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentSecurityServiceServer is the server API for ContentSecurityService service.
// All implementations must embed UnimplementedContentSecurityServiceServer
// for forward compatibility.
type ContentSecurityServiceServer interface {
	SanitizeContent(context.Context, *SanitizeContentRequest) (*SanitizeContentResponse, error)
	mustEmbedUnimplementedContentSecurityServiceServer()
}

// UnimplementedContentSecurityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a panic
// when methods are called on the UnimplementedContentSecurityServiceServer
// without embedding the proto-generated server.
type UnimplementedContentSecurityServiceServer struct{}

func (UnimplementedContentSecurityServiceServer) SanitizeContent(context.Context, *SanitizeContentRequest) (*SanitizeContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SanitizeContent not implemented")
}

func (UnimplementedContentSecurityServiceServer) mustEmbedUnimplementedContentSecurityServiceServer() {
}

// UnsafeContentSecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentSecurityServiceServer will
// result in compilation errors.
type UnsafeContentSecurityServiceServer interface {
	mustEmbedUnimplementedContentSecurityServiceServer()
}

func RegisterContentSecurityServiceServer(s grpc.ServiceRegistrar, srv ContentSecurityServiceServer) {
	s.RegisterService(&ContentSecurityService_ServiceDesc, srv)
}

func _ContentSecurityService_SanitizeContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SanitizeContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentSecurityServiceServer).SanitizeContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentSecurityService_SanitizeContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentSecurityServiceServer).SanitizeContent(ctx, req.(*SanitizeContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentSecurityService_ServiceDesc is the grpc.ServiceDesc for ContentSecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentSecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content_security.ContentSecurityService",
	HandlerType: (*ContentSecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SanitizeContent",
			Handler:    _ContentSecurityService_SanitizeContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content_security.proto",
}
