// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	comment "sea-try-go/service/comment/api/internal/handler/comment"
	"sea-try-go/service/comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/comment/create",
				Handler: comment.CreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/delete",
				Handler: comment.DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/like",
				Handler: comment.LikeCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/list",
				Handler: comment.GetCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/manage",
				Handler: comment.ManageCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/report",
				Handler: comment.ReportCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/subject/state",
				Handler: comment.UpdateSubjectStateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
