// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	GetFolderByID(ctx context.Context, id int64) (Folder, error)
	ListFoldersByUser(ctx context.Context, userID int64) ([]Folder, error)
	SoftDeleteFolder(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
