// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/like.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 操作类型枚举
type ActionType int32

const (
	ActionType_ACTION_UNSPECIFIED ActionType = 0
	// 点赞
	ActionType_ACTION_LIKE ActionType = 1
	// 取消点赞
	ActionType_ACTION_UNLIKE ActionType = 2
	// 点踩
	ActionType_ACTION_DISLIKE ActionType = 3
	// 取消点踩
	ActionType_ACTION_UNDISLIKE ActionType = 4
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_LIKE",
		2: "ACTION_UNLIKE",
		3: "ACTION_DISLIKE",
		4: "ACTION_UNDISLIKE",
	}
	ActionType_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_LIKE":        1,
		"ACTION_UNLIKE":      2,
		"ACTION_DISLIKE":     3,
		"ACTION_UNDISLIKE":   4,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_like_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_proto_like_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{0}
}

type LikeActionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标对象类型,例如article,video等
	TargetType string `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// 目标对象id,和type联合起来使用
	// target_type = article && target_id = 1 表示文章中id为1的那个对象
	TargetId string `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 点赞者ID
	UserId int64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 操作类型
	ActionType ActionType `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3,enum=pb.ActionType" json:"action_type,omitempty"`
	// 作者ID
	AuthorId int64 `protobuf:"varint,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// 点赞权重,用于推广系统计算
	Weight float32 `protobuf:"fixed32,6,opt,name=weight,proto3" json:"weight,omitempty"`
	// 客户端IP,防刷机制AntiBrush中使用
	ClientIp string `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// 推广任务ID,对接 Kafka 推广系统结算
	PromotionId   string `protobuf:"bytes,8,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeActionReq) Reset() {
	*x = LikeActionReq{}
	mi := &file_proto_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeActionReq) ProtoMessage() {}

func (x *LikeActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeActionReq.ProtoReflect.Descriptor instead.
func (*LikeActionReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{0}
}

func (x *LikeActionReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *LikeActionReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *LikeActionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeActionReq) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_UNSPECIFIED
}

func (x *LikeActionReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *LikeActionReq) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *LikeActionReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LikeActionReq) GetPromotionId() string {
	if x != nil {
		return x.PromotionId
	}
	return ""
}

type LikeActionResp struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 相关信息,成功为Success,失败则返回失败信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 操作后的点赞数
	LikeCount     int64 `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeActionResp) Reset() {
	*x = LikeActionResp{}
	mi := &file_proto_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeActionResp) ProtoMessage() {}

func (x *LikeActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeActionResp.ProtoReflect.Descriptor instead.
func (*LikeActionResp) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{1}
}

func (x *LikeActionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LikeActionResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LikeActionResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

// 对稿件的点赞数查询
type GetLikeCountReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TargetType string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// 支持单个稿件的点赞查询,也支持批量查询(Feed流列表页刚需)
	TargetIds     []string `protobuf:"bytes,2,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeCountReq) Reset() {
	*x = GetLikeCountReq{}
	mi := &file_proto_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCountReq) ProtoMessage() {}

func (x *GetLikeCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCountReq.ProtoReflect.Descriptor instead.
func (*GetLikeCountReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{2}
}

func (x *GetLikeCountReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *GetLikeCountReq) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

// 点赞数结构,包括赞和踩
type LikeCountItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 点赞数
	LikeCount int64 `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	// 点踩数
	DislikeCount  int64 `protobuf:"varint,2,opt,name=dislike_count,json=dislikeCount,proto3" json:"dislike_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCountItem) Reset() {
	*x = LikeCountItem{}
	mi := &file_proto_like_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCountItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCountItem) ProtoMessage() {}

func (x *LikeCountItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCountItem.ProtoReflect.Descriptor instead.
func (*LikeCountItem) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{3}
}

func (x *LikeCountItem) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *LikeCountItem) GetDislikeCount() int64 {
	if x != nil {
		return x.DislikeCount
	}
	return 0
}

type GetLikeCountResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key为target_id,Value为对应的点赞点踩数
	Counts        map[string]*LikeCountItem `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeCountResp) Reset() {
	*x = GetLikeCountResp{}
	mi := &file_proto_like_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCountResp) ProtoMessage() {}

func (x *GetLikeCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCountResp.ProtoReflect.Descriptor instead.
func (*GetLikeCountResp) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{4}
}

func (x *GetLikeCountResp) GetCounts() map[string]*LikeCountItem {
	if x != nil {
		return x.Counts
	}
	return nil
}

// 查询某人的点赞状态
type GetLikeStateReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TargetType string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// 用户ID
	UserId        int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetIds     []string `protobuf:"bytes,3,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeStateReq) Reset() {
	*x = GetLikeStateReq{}
	mi := &file_proto_like_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeStateReq) ProtoMessage() {}

func (x *GetLikeStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeStateReq.ProtoReflect.Descriptor instead.
func (*GetLikeStateReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{5}
}

func (x *GetLikeStateReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *GetLikeStateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLikeStateReq) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type GetLikeStateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        map[string]int32       `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeStateResp) Reset() {
	*x = GetLikeStateResp{}
	mi := &file_proto_like_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeStateResp) ProtoMessage() {}

func (x *GetLikeStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeStateResp.ProtoReflect.Descriptor instead.
func (*GetLikeStateResp) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{6}
}

func (x *GetLikeStateResp) GetStates() map[string]int32 {
	if x != nil {
		return x.States
	}
	return nil
}

// 获取某人的点赞列表
type GetUserLikeListReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TargetType string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	UserId     int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 上一页最后一条记录的时间戳
	Cursor int64 `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// 每一页的大小
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLikeListReq) Reset() {
	*x = GetUserLikeListReq{}
	mi := &file_proto_like_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLikeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikeListReq) ProtoMessage() {}

func (x *GetUserLikeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikeListReq.ProtoReflect.Descriptor instead.
func (*GetUserLikeListReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserLikeListReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *GetUserLikeListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserLikeListReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetUserLikeListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 点赞记录结构
type LikeRecordItem struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TargetId string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 时间戳
	Timestamp     int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRecordItem) Reset() {
	*x = LikeRecordItem{}
	mi := &file_proto_like_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRecordItem) ProtoMessage() {}

func (x *LikeRecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRecordItem.ProtoReflect.Descriptor instead.
func (*LikeRecordItem) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{8}
}

func (x *LikeRecordItem) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *LikeRecordItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetUserLikeListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	List  []*LikeRecordItem      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 是否到头了
	IsEnd bool `protobuf:"varint,2,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	// 返回接下来查询的游标位置
	NextCursor    int64 `protobuf:"varint,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLikeListResp) Reset() {
	*x = GetUserLikeListResp{}
	mi := &file_proto_like_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLikeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikeListResp) ProtoMessage() {}

func (x *GetUserLikeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikeListResp.ProtoReflect.Descriptor instead.
func (*GetUserLikeListResp) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserLikeListResp) GetList() []*LikeRecordItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserLikeListResp) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *GetUserLikeListResp) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

// 查询某个稿件的点赞人列表
type GetTargetLikerListReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TargetType string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId   string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// cursor含义同上
	Cursor        int64 `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetLikerListReq) Reset() {
	*x = GetTargetLikerListReq{}
	mi := &file_proto_like_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetLikerListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetLikerListReq) ProtoMessage() {}

func (x *GetTargetLikerListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetLikerListReq.ProtoReflect.Descriptor instead.
func (*GetTargetLikerListReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{10}
}

func (x *GetTargetLikerListReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *GetTargetLikerListReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GetTargetLikerListReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetTargetLikerListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 点赞人结构
type LikeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeItem) Reset() {
	*x = LikeItem{}
	mi := &file_proto_like_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeItem) ProtoMessage() {}

func (x *LikeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeItem.ProtoReflect.Descriptor instead.
func (*LikeItem) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{11}
}

func (x *LikeItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetTargetLikerListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*LikeItem            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	IsEnd         bool                   `protobuf:"varint,2,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	NextCursor    int64                  `protobuf:"varint,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetLikerListResp) Reset() {
	*x = GetTargetLikerListResp{}
	mi := &file_proto_like_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetLikerListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetLikerListResp) ProtoMessage() {}

func (x *GetTargetLikerListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetLikerListResp.ProtoReflect.Descriptor instead.
func (*GetTargetLikerListResp) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{12}
}

func (x *GetTargetLikerListResp) GetList() []*LikeItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetTargetLikerListResp) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *GetTargetLikerListResp) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

// 获取某人的总获赞数
type GetUserTotalLikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTotalLikeReq) Reset() {
	*x = GetUserTotalLikeReq{}
	mi := &file_proto_like_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTotalLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTotalLikeReq) ProtoMessage() {}

func (x *GetUserTotalLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTotalLikeReq.ProtoReflect.Descriptor instead.
func (*GetUserTotalLikeReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserTotalLikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserTotalLikeResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalLikeCount int64                  `protobuf:"varint,1,opt,name=total_like_count,json=totalLikeCount,proto3" json:"total_like_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserTotalLikeResp) Reset() {
	*x = GetUserTotalLikeResp{}
	mi := &file_proto_like_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTotalLikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTotalLikeResp) ProtoMessage() {}

func (x *GetUserTotalLikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTotalLikeResp.ProtoReflect.Descriptor instead.
func (*GetUserTotalLikeResp) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserTotalLikeResp) GetTotalLikeCount() int64 {
	if x != nil {
		return x.TotalLikeCount
	}
	return 0
}

var File_proto_like_proto protoreflect.FileDescriptor

const file_proto_like_proto_rawDesc = "" +
	"\n" +
	"\x10proto/like.proto\x12\x02pb\"\x8c\x02\n" +
	"\rLikeActionReq\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12/\n" +
	"\vaction_type\x18\x04 \x01(\x0e2\x0e.pb.ActionTypeR\n" +
	"actionType\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x02R\x06weight\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\tR\bclientIp\x12!\n" +
	"\fpromotion_id\x18\b \x01(\tR\vpromotionId\"c\n" +
	"\x0eLikeActionResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"like_count\x18\x03 \x01(\x03R\tlikeCount\"Q\n" +
	"\x0fGetLikeCountReq\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x02 \x03(\tR\ttargetIds\"S\n" +
	"\rLikeCountItem\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\x12#\n" +
	"\rdislike_count\x18\x02 \x01(\x03R\fdislikeCount\"\x9a\x01\n" +
	"\x10GetLikeCountResp\x128\n" +
	"\x06counts\x18\x01 \x03(\v2 .pb.GetLikeCountResp.CountsEntryR\x06counts\x1aL\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.pb.LikeCountItemR\x05value:\x028\x01\"j\n" +
	"\x0fGetLikeStateReq\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x03 \x03(\tR\ttargetIds\"\x87\x01\n" +
	"\x10GetLikeStateResp\x128\n" +
	"\x06states\x18\x01 \x03(\v2 .pb.GetLikeStateResp.StatesEntryR\x06states\x1a9\n" +
	"\vStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x83\x01\n" +
	"\x12GetUserLikeListReq\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"K\n" +
	"\x0eLikeRecordItem\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"u\n" +
	"\x13GetUserLikeListResp\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.pb.LikeRecordItemR\x04list\x12\x15\n" +
	"\x06is_end\x18\x02 \x01(\bR\x05isEnd\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\x03R\n" +
	"nextCursor\"\x8a\x01\n" +
	"\x15GetTargetLikerListReq\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"A\n" +
	"\bLikeItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"r\n" +
	"\x16GetTargetLikerListResp\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.pb.LikeItemR\x04list\x12\x15\n" +
	"\x06is_end\x18\x02 \x01(\bR\x05isEnd\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\x03R\n" +
	"nextCursor\".\n" +
	"\x13GetUserTotalLikeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"@\n" +
	"\x14GetUserTotalLikeResp\x12(\n" +
	"\x10total_like_count\x18\x01 \x01(\x03R\x0etotalLikeCount*r\n" +
	"\n" +
	"ActionType\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vACTION_LIKE\x10\x01\x12\x11\n" +
	"\rACTION_UNLIKE\x10\x02\x12\x12\n" +
	"\x0eACTION_DISLIKE\x10\x03\x12\x14\n" +
	"\x10ACTION_UNDISLIKE\x10\x042\x90\x03\n" +
	"\vLikeService\x123\n" +
	"\n" +
	"LikeAction\x12\x11.pb.LikeActionReq\x1a\x12.pb.LikeActionResp\x129\n" +
	"\fGetLikeCount\x12\x13.pb.GetLikeCountReq\x1a\x14.pb.GetLikeCountResp\x129\n" +
	"\fGetLikeState\x12\x13.pb.GetLikeStateReq\x1a\x14.pb.GetLikeStateResp\x12B\n" +
	"\x0fGetUserLikeList\x12\x16.pb.GetUserLikeListReq\x1a\x17.pb.GetUserLikeListResp\x12K\n" +
	"\x12GetTargetLikerList\x12\x19.pb.GetTargetLikerListReq\x1a\x1a.pb.GetTargetLikerListResp\x12E\n" +
	"\x10GetUserTotalLike\x12\x17.pb.GetUserTotalLikeReq\x1a\x18.pb.GetUserTotalLikeRespB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_like_proto_rawDescOnce sync.Once
	file_proto_like_proto_rawDescData []byte
)

func file_proto_like_proto_rawDescGZIP() []byte {
	file_proto_like_proto_rawDescOnce.Do(func() {
		file_proto_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_like_proto_rawDesc), len(file_proto_like_proto_rawDesc)))
	})
	return file_proto_like_proto_rawDescData
}

var file_proto_like_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_like_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_like_proto_goTypes = []any{
	(ActionType)(0),                // 0: pb.ActionType
	(*LikeActionReq)(nil),          // 1: pb.LikeActionReq
	(*LikeActionResp)(nil),         // 2: pb.LikeActionResp
	(*GetLikeCountReq)(nil),        // 3: pb.GetLikeCountReq
	(*LikeCountItem)(nil),          // 4: pb.LikeCountItem
	(*GetLikeCountResp)(nil),       // 5: pb.GetLikeCountResp
	(*GetLikeStateReq)(nil),        // 6: pb.GetLikeStateReq
	(*GetLikeStateResp)(nil),       // 7: pb.GetLikeStateResp
	(*GetUserLikeListReq)(nil),     // 8: pb.GetUserLikeListReq
	(*LikeRecordItem)(nil),         // 9: pb.LikeRecordItem
	(*GetUserLikeListResp)(nil),    // 10: pb.GetUserLikeListResp
	(*GetTargetLikerListReq)(nil),  // 11: pb.GetTargetLikerListReq
	(*LikeItem)(nil),               // 12: pb.LikeItem
	(*GetTargetLikerListResp)(nil), // 13: pb.GetTargetLikerListResp
	(*GetUserTotalLikeReq)(nil),    // 14: pb.GetUserTotalLikeReq
	(*GetUserTotalLikeResp)(nil),   // 15: pb.GetUserTotalLikeResp
	nil,                            // 16: pb.GetLikeCountResp.CountsEntry
	nil,                            // 17: pb.GetLikeStateResp.StatesEntry
}
var file_proto_like_proto_depIdxs = []int32{
	0,  // 0: pb.LikeActionReq.action_type:type_name -> pb.ActionType
	16, // 1: pb.GetLikeCountResp.counts:type_name -> pb.GetLikeCountResp.CountsEntry
	17, // 2: pb.GetLikeStateResp.states:type_name -> pb.GetLikeStateResp.StatesEntry
	9,  // 3: pb.GetUserLikeListResp.list:type_name -> pb.LikeRecordItem
	12, // 4: pb.GetTargetLikerListResp.list:type_name -> pb.LikeItem
	4,  // 5: pb.GetLikeCountResp.CountsEntry.value:type_name -> pb.LikeCountItem
	1,  // 6: pb.LikeService.LikeAction:input_type -> pb.LikeActionReq
	3,  // 7: pb.LikeService.GetLikeCount:input_type -> pb.GetLikeCountReq
	6,  // 8: pb.LikeService.GetLikeState:input_type -> pb.GetLikeStateReq
	8,  // 9: pb.LikeService.GetUserLikeList:input_type -> pb.GetUserLikeListReq
	11, // 10: pb.LikeService.GetTargetLikerList:input_type -> pb.GetTargetLikerListReq
	14, // 11: pb.LikeService.GetUserTotalLike:input_type -> pb.GetUserTotalLikeReq
	2,  // 12: pb.LikeService.LikeAction:output_type -> pb.LikeActionResp
	5,  // 13: pb.LikeService.GetLikeCount:output_type -> pb.GetLikeCountResp
	7,  // 14: pb.LikeService.GetLikeState:output_type -> pb.GetLikeStateResp
	10, // 15: pb.LikeService.GetUserLikeList:output_type -> pb.GetUserLikeListResp
	13, // 16: pb.LikeService.GetTargetLikerList:output_type -> pb.GetTargetLikerListResp
	15, // 17: pb.LikeService.GetUserTotalLike:output_type -> pb.GetUserTotalLikeResp
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_like_proto_init() }
func file_proto_like_proto_init() {
	if File_proto_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_like_proto_rawDesc), len(file_proto_like_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_like_proto_goTypes,
		DependencyIndexes: file_proto_like_proto_depIdxs,
		EnumInfos:         file_proto_like_proto_enumTypes,
		MessageInfos:      file_proto_like_proto_msgTypes,
	}.Build()
	File_proto_like_proto = out.File
	file_proto_like_proto_goTypes = nil
	file_proto_like_proto_depIdxs = nil
}
