// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: proto/like.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LikeService_LikeAction_FullMethodName         = "/pb.LikeService/LikeAction"
	LikeService_GetLikeCount_FullMethodName       = "/pb.LikeService/GetLikeCount"
	LikeService_GetLikeState_FullMethodName       = "/pb.LikeService/GetLikeState"
	LikeService_GetUserLikeList_FullMethodName    = "/pb.LikeService/GetUserLikeList"
	LikeService_GetTargetLikerList_FullMethodName = "/pb.LikeService/GetTargetLikerList"
	LikeService_GetUserTotalLike_FullMethodName   = "/pb.LikeService/GetUserTotalLike"
)

// LikeServiceClient is the client API for LikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikeServiceClient interface {
	LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionResp, error)
	GetLikeCount(ctx context.Context, in *GetLikeCountReq, opts ...grpc.CallOption) (*GetLikeCountResp, error)
	GetLikeState(ctx context.Context, in *GetLikeStateReq, opts ...grpc.CallOption) (*GetLikeStateResp, error)
	GetUserLikeList(ctx context.Context, in *GetUserLikeListReq, opts ...grpc.CallOption) (*GetUserLikeListResp, error)
	GetTargetLikerList(ctx context.Context, in *GetTargetLikerListReq, opts ...grpc.CallOption) (*GetTargetLikerListResp, error)
	GetUserTotalLike(ctx context.Context, in *GetUserTotalLikeReq, opts ...grpc.CallOption) (*GetUserTotalLikeResp, error)
}

type likeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeServiceClient(cc grpc.ClientConnInterface) LikeServiceClient {
	return &likeServiceClient{cc}
}

func (c *likeServiceClient) LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeActionResp)
	err := c.cc.Invoke(ctx, LikeService_LikeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) GetLikeCount(ctx context.Context, in *GetLikeCountReq, opts ...grpc.CallOption) (*GetLikeCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikeCountResp)
	err := c.cc.Invoke(ctx, LikeService_GetLikeCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) GetLikeState(ctx context.Context, in *GetLikeStateReq, opts ...grpc.CallOption) (*GetLikeStateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikeStateResp)
	err := c.cc.Invoke(ctx, LikeService_GetLikeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) GetUserLikeList(ctx context.Context, in *GetUserLikeListReq, opts ...grpc.CallOption) (*GetUserLikeListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLikeListResp)
	err := c.cc.Invoke(ctx, LikeService_GetUserLikeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) GetTargetLikerList(ctx context.Context, in *GetTargetLikerListReq, opts ...grpc.CallOption) (*GetTargetLikerListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTargetLikerListResp)
	err := c.cc.Invoke(ctx, LikeService_GetTargetLikerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) GetUserTotalLike(ctx context.Context, in *GetUserTotalLikeReq, opts ...grpc.CallOption) (*GetUserTotalLikeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTotalLikeResp)
	err := c.cc.Invoke(ctx, LikeService_GetUserTotalLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeServiceServer is the server API for LikeService service.
// All implementations must embed UnimplementedLikeServiceServer
// for forward compatibility.
type LikeServiceServer interface {
	LikeAction(context.Context, *LikeActionReq) (*LikeActionResp, error)
	GetLikeCount(context.Context, *GetLikeCountReq) (*GetLikeCountResp, error)
	GetLikeState(context.Context, *GetLikeStateReq) (*GetLikeStateResp, error)
	GetUserLikeList(context.Context, *GetUserLikeListReq) (*GetUserLikeListResp, error)
	GetTargetLikerList(context.Context, *GetTargetLikerListReq) (*GetTargetLikerListResp, error)
	GetUserTotalLike(context.Context, *GetUserTotalLikeReq) (*GetUserTotalLikeResp, error)
	mustEmbedUnimplementedLikeServiceServer()
}

// UnimplementedLikeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLikeServiceServer struct{}

func (UnimplementedLikeServiceServer) LikeAction(context.Context, *LikeActionReq) (*LikeActionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeAction not implemented")
}
func (UnimplementedLikeServiceServer) GetLikeCount(context.Context, *GetLikeCountReq) (*GetLikeCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikeCount not implemented")
}
func (UnimplementedLikeServiceServer) GetLikeState(context.Context, *GetLikeStateReq) (*GetLikeStateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikeState not implemented")
}
func (UnimplementedLikeServiceServer) GetUserLikeList(context.Context, *GetUserLikeListReq) (*GetUserLikeListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserLikeList not implemented")
}
func (UnimplementedLikeServiceServer) GetTargetLikerList(context.Context, *GetTargetLikerListReq) (*GetTargetLikerListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTargetLikerList not implemented")
}
func (UnimplementedLikeServiceServer) GetUserTotalLike(context.Context, *GetUserTotalLikeReq) (*GetUserTotalLikeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTotalLike not implemented")
}
func (UnimplementedLikeServiceServer) mustEmbedUnimplementedLikeServiceServer() {}
func (UnimplementedLikeServiceServer) testEmbeddedByValue()                     {}

// UnsafeLikeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeServiceServer will
// result in compilation errors.
type UnsafeLikeServiceServer interface {
	mustEmbedUnimplementedLikeServiceServer()
}

func RegisterLikeServiceServer(s grpc.ServiceRegistrar, srv LikeServiceServer) {
	// If the following call panics, it indicates UnimplementedLikeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LikeService_ServiceDesc, srv)
}

func _LikeService_LikeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).LikeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_LikeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).LikeAction(ctx, req.(*LikeActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_GetLikeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikeCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).GetLikeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_GetLikeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).GetLikeCount(ctx, req.(*GetLikeCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_GetLikeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikeStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).GetLikeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_GetLikeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).GetLikeState(ctx, req.(*GetLikeStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_GetUserLikeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLikeListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).GetUserLikeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_GetUserLikeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).GetUserLikeList(ctx, req.(*GetUserLikeListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_GetTargetLikerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetLikerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).GetTargetLikerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_GetTargetLikerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).GetTargetLikerList(ctx, req.(*GetTargetLikerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_GetUserTotalLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTotalLikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).GetUserTotalLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_GetUserTotalLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).GetUserTotalLike(ctx, req.(*GetUserTotalLikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LikeService_ServiceDesc is the grpc.ServiceDesc for LikeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LikeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LikeService",
	HandlerType: (*LikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikeAction",
			Handler:    _LikeService_LikeAction_Handler,
		},
		{
			MethodName: "GetLikeCount",
			Handler:    _LikeService_GetLikeCount_Handler,
		},
		{
			MethodName: "GetLikeState",
			Handler:    _LikeService_GetLikeState_Handler,
		},
		{
			MethodName: "GetUserLikeList",
			Handler:    _LikeService_GetUserLikeList_Handler,
		},
		{
			MethodName: "GetTargetLikerList",
			Handler:    _LikeService_GetTargetLikerList_Handler,
		},
		{
			MethodName: "GetUserTotalLike",
			Handler:    _LikeService_GetUserTotalLike_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/like.proto",
}
