// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/content_security.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SanitizeContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Options       *SanitizeOptions       `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeContentRequest) Reset() {
	*x = SanitizeContentRequest{}
	mi := &file_proto_content_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeContentRequest) ProtoMessage() {}

func (x *SanitizeContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeContentRequest.ProtoReflect.Descriptor instead.
func (*SanitizeContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_security_proto_rawDescGZIP(), []int{0}
}

func (x *SanitizeContentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SanitizeContentRequest) GetOptions() *SanitizeOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type SanitizeOptions struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	EnableHtmlSanitization        bool                   `protobuf:"varint,1,opt,name=enable_html_sanitization,json=enableHtmlSanitization,proto3" json:"enable_html_sanitization,omitempty"`
	EnableAdDetection             bool                   `protobuf:"varint,2,opt,name=enable_ad_detection,json=enableAdDetection,proto3" json:"enable_ad_detection,omitempty"`
	EnableUnicodeNormalization    bool                   `protobuf:"varint,3,opt,name=enable_unicode_normalization,json=enableUnicodeNormalization,proto3" json:"enable_unicode_normalization,omitempty"`
	EnableWhitespaceNormalization bool                   `protobuf:"varint,4,opt,name=enable_whitespace_normalization,json=enableWhitespaceNormalization,proto3" json:"enable_whitespace_normalization,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SanitizeOptions) Reset() {
	*x = SanitizeOptions{}
	mi := &file_proto_content_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeOptions) ProtoMessage() {}

func (x *SanitizeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeOptions.ProtoReflect.Descriptor instead.
func (*SanitizeOptions) Descriptor() ([]byte, []int) {
	return file_proto_content_security_proto_rawDescGZIP(), []int{1}
}

func (x *SanitizeOptions) GetEnableHtmlSanitization() bool {
	if x != nil {
		return x.EnableHtmlSanitization
	}
	return false
}

func (x *SanitizeOptions) GetEnableAdDetection() bool {
	if x != nil {
		return x.EnableAdDetection
	}
	return false
}

func (x *SanitizeOptions) GetEnableUnicodeNormalization() bool {
	if x != nil {
		return x.EnableUnicodeNormalization
	}
	return false
}

func (x *SanitizeOptions) GetEnableWhitespaceNormalization() bool {
	if x != nil {
		return x.EnableWhitespaceNormalization
	}
	return false
}

type SanitizeContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SanitizedText string                 `protobuf:"bytes,1,opt,name=sanitized_text,json=sanitizedText,proto3" json:"sanitized_text,omitempty"`
	IsAd          bool                   `protobuf:"varint,2,opt,name=is_ad,json=isAd,proto3" json:"is_ad,omitempty"`
	AdConfidence  float32                `protobuf:"fixed32,3,opt,name=ad_confidence,json=adConfidence,proto3" json:"ad_confidence,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeContentResponse) Reset() {
	*x = SanitizeContentResponse{}
	mi := &file_proto_content_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeContentResponse) ProtoMessage() {}

func (x *SanitizeContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeContentResponse.ProtoReflect.Descriptor instead.
func (*SanitizeContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_security_proto_rawDescGZIP(), []int{2}
}

func (x *SanitizeContentResponse) GetSanitizedText() string {
	if x != nil {
		return x.SanitizedText
	}
	return ""
}

func (x *SanitizeContentResponse) GetIsAd() bool {
	if x != nil {
		return x.IsAd
	}
	return false
}

func (x *SanitizeContentResponse) GetAdConfidence() float32 {
	if x != nil {
		return x.AdConfidence
	}
	return 0
}

func (x *SanitizeContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SanitizeContentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_content_security_proto protoreflect.FileDescriptor

const file_proto_content_security_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/content_security.proto\x12\x10content_security\"i\n" +
	"\x16SanitizeContentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12;\n" +
	"\aoptions\x18\x02 \x01(\v2!.content_security.SanitizeOptionsR\aoptions\"\x85\x02\n" +
	"\x0fSanitizeOptions\x128\n" +
	"\x18enable_html_sanitization\x18\x01 \x01(\bR\x16enableHtmlSanitization\x12.\n" +
	"\x13enable_ad_detection\x18\x02 \x01(\bR\x11enableAdDetection\x12@\n" +
	"\x1cenable_unicode_normalization\x18\x03 \x01(\bR\x1aenableUnicodeNormalization\x12F\n" +
	"\x1fenable_whitespace_normalization\x18\x04 \x01(\bR\x1denableWhitespaceNormalization\"\xb9\x01\n" +
	"\x17SanitizeContentResponse\x12%\n" +
	"\x0esanitized_text\x18\x01 \x01(\tR\rsanitizedText\x12\x13\n" +
	"\x05is_ad\x18\x02 \x01(\bR\x04isAd\x12#\n" +
	"\rad_confidence\x18\x03 \x01(\x02R\fadConfidence\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage2\x80\x01\n" +
	"\x16ContentSecurityService\x12f\n" +
	"\x0fSanitizeContent\x12(.content_security.SanitizeContentRequest\x1a).content_security.SanitizeContentResponseB,Z*sea-try-go/service/content-security/rpc/pbb\x06proto3"

var (
	file_proto_content_security_proto_rawDescOnce sync.Once
	file_proto_content_security_proto_rawDescData []byte
)

func file_proto_content_security_proto_rawDescGZIP() []byte {
	file_proto_content_security_proto_rawDescOnce.Do(func() {
		file_proto_content_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_security_proto_rawDesc), len(file_proto_content_security_proto_rawDesc)))
	})
	return file_proto_content_security_proto_rawDescData
}

var file_proto_content_security_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_content_security_proto_goTypes = []any{
	(*SanitizeContentRequest)(nil),  // 0: content_security.SanitizeContentRequest
	(*SanitizeOptions)(nil),         // 1: content_security.SanitizeOptions
	(*SanitizeContentResponse)(nil), // 2: content_security.SanitizeContentResponse
}
var file_proto_content_security_proto_depIdxs = []int32{
	1, // 0: content_security.SanitizeContentRequest.options:type_name -> content_security.SanitizeOptions
	0, // 1: content_security.ContentSecurityService.SanitizeContent:input_type -> content_security.SanitizeContentRequest
	2, // 2: content_security.ContentSecurityService.SanitizeContent:output_type -> content_security.SanitizeContentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_content_security_proto_init() }
func file_proto_content_security_proto_init() {
	if File_proto_content_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_security_proto_rawDesc), len(file_proto_content_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_content_security_proto_goTypes,
		DependencyIndexes: file_proto_content_security_proto_depIdxs,
		MessageInfos:      file_proto_content_security_proto_msgTypes,
	}.Build()
	File_proto_content_security_proto = out.File
	file_proto_content_security_proto_goTypes = nil
	file_proto_content_security_proto_depIdxs = nil
}
