// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hotspot.proto

package server

import (
	"context"

	"sea-try-go/service/hotspot/rpc/internal/logic"
	"sea-try-go/service/hotspot/rpc/internal/svc"
	"sea-try-go/service/hotspot/rpc/pb"
)

type ArticleServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedArticleServiceServer
}

func NewArticleServiceServer(svcCtx *svc.ServiceContext) *ArticleServiceServer {
	return &ArticleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServiceServer) LikeArticle(ctx context.Context, in *__.LikeArticleReq) (*__.LikeArticleResp, error) {
	l := logic.NewLikeArticleLogic(ctx, s.svcCtx)
	return l.LikeArticle(in)
}
