// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hotspot.proto

package server

import (
	"context"

	"sea-try-go/service/hotspot/rpc/internal/logic"
	"sea-try-go/service/hotspot/rpc/internal/svc"
	"sea-try-go/service/hotspot/rpc/pb"
)

type HotspotServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedHotspotServiceServer
}

func NewHotspotServiceServer(svcCtx *svc.ServiceContext) *HotspotServiceServer {
	return &HotspotServiceServer{
		svcCtx: svcCtx,
	}
}

// 点赞/取消点赞
func (s *HotspotServiceServer) ToggleLike(ctx context.Context, in *__.LikeReq) (*__.LikeResp, error) {
	l := logic.NewToggleLikeLogic(ctx, s.svcCtx)
	return l.ToggleLike(in)
}

// 查询是否点赞过
func (s *HotspotServiceServer) IsLiked(ctx context.Context, in *__.IsLikedReq) (*__.IsLikedResp, error) {
	l := logic.NewIsLikedLogic(ctx, s.svcCtx)
	return l.IsLiked(in)
}

// 发表评论
func (s *HotspotServiceServer) CreateComment(ctx context.Context, in *__.CommentReq) (*__.CommentResp, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

// 获取评论列表
func (s *HotspotServiceServer) ListComments(ctx context.Context, in *__.ListCommentReq) (*__.ListCommentResp, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}
