// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: task.proto

package server

import (
	"context"

	"sea-try-go/service/task/rpc/internal/logic"
	"sea-try-go/service/task/rpc/internal/svc"
	"sea-try-go/service/task/rpc/pb"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServiceServer) GetTask(ctx context.Context, in *__.GetTaskReq) (*__.GetTaskResp, error) {
	l := logic.NewGetTaskLogic(ctx, s.svcCtx)
	return l.GetTask(in)
}
