// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articlesFieldNames          = builder.RawFieldNames(&Articles{}, true)
	articlesRows                = strings.Join(articlesFieldNames, ",")
	articlesRowsExpectAutoSet   = strings.Join(stringx.Remove(articlesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	articlesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(articlesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicArticlesIdPrefix = "cache:public:articles:id:"
)

type (
	articlesModel interface {
		Insert(ctx context.Context, data *Articles) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Articles, error)
		Update(ctx context.Context, data *Articles) error
		Delete(ctx context.Context, id int64) error
	}

	defaultArticlesModel struct {
		sqlc.CachedConn
		table string
	}

	Articles struct {
		Id         int64     `db:"id"`
		Title      string    `db:"title"`
		Content    string    `db:"content"`
		Author     string    `db:"author"`
		Status     int64     `db:"status"`
		StorageUrl string    `db:"storage_url"`
		CreatedAt  time.Time `db:"created_at"`
		UpdatedAt  time.Time `db:"updated_at"`
	}
)

func newArticlesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultArticlesModel {
	return &defaultArticlesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."articles"`,
	}
}

func (m *defaultArticlesModel) Delete(ctx context.Context, id int64) error {
	publicArticlesIdKey := fmt.Sprintf("%s%v", cachePublicArticlesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicArticlesIdKey)
	return err
}

func (m *defaultArticlesModel) FindOne(ctx context.Context, id int64) (*Articles, error) {
	publicArticlesIdKey := fmt.Sprintf("%s%v", cachePublicArticlesIdPrefix, id)
	var resp Articles
	err := m.QueryRowCtx(ctx, &resp, publicArticlesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", articlesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticlesModel) Insert(ctx context.Context, data *Articles) (sql.Result, error) {
	publicArticlesIdKey := fmt.Sprintf("%s%v", cachePublicArticlesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, articlesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Title, data.Content, data.Author, data.Status, data.StorageUrl)
	}, publicArticlesIdKey)
	return ret, err
}

func (m *defaultArticlesModel) Update(ctx context.Context, data *Articles) error {
	publicArticlesIdKey := fmt.Sprintf("%s%v", cachePublicArticlesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, articlesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Title, data.Content, data.Author, data.Status, data.StorageUrl)
	}, publicArticlesIdKey)
	return err
}

func (m *defaultArticlesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicArticlesIdPrefix, primary)
}

func (m *defaultArticlesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", articlesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultArticlesModel) tableName() string {
	return m.table
}
