// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hotspot.proto

package articleservice

import (
	"context"

	"sea-try-go/service/hotspot/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LikeArticleReq  = __.LikeArticleReq
	LikeArticleResp = __.LikeArticleResp

	ArticleService interface {
		LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error)
	}

	defaultArticleService struct {
		cli zrpc.Client
	}
)

func NewArticleService(cli zrpc.Client) ArticleService {
	return &defaultArticleService{
		cli: cli,
	}
}

func (m *defaultArticleService) LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error) {
	client := __.NewArticleServiceClient(m.cli.Conn())
	return client.LikeArticle(ctx, in, opts...)
}
