// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: points.proto

package server

import (
	"context"

	"sea-try-go/service/points/rpc/internal/logic"
	"sea-try-go/service/points/rpc/internal/svc"
	"sea-try-go/service/points/rpc/pb"
)

type PointsServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedPointsServiceServer
}

func NewPointsServiceServer(svcCtx *svc.ServiceContext) *PointsServiceServer {
	return &PointsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PointsServiceServer) Points(ctx context.Context, in *__.PointsReq) (*__.PointsResp, error) {
	l := logic.NewPointsLogic(ctx, s.svcCtx)
	return l.Points(in)
}
