// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/article.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文章业务状态（仅描述社区场景下的状态）
type ArticleStatus int32

const (
	ArticleStatus_ARTICLE_STATUS_UNSPECIFIED ArticleStatus = 0 // 未指定
	ArticleStatus_DRAFT                      ArticleStatus = 1 // 草稿
	ArticleStatus_PUBLISHED                  ArticleStatus = 2 // 已发布
	ArticleStatus_REVIEWING                  ArticleStatus = 3 // 审核中（社区必备）
	ArticleStatus_REJECTED                   ArticleStatus = 4 // 审核被拒
	ArticleStatus_DELETED                    ArticleStatus = 5 // 已删除（逻辑删除）
)

// Enum value maps for ArticleStatus.
var (
	ArticleStatus_name = map[int32]string{
		0: "ARTICLE_STATUS_UNSPECIFIED",
		1: "DRAFT",
		2: "PUBLISHED",
		3: "REVIEWING",
		4: "REJECTED",
		5: "DELETED",
	}
	ArticleStatus_value = map[string]int32{
		"ARTICLE_STATUS_UNSPECIFIED": 0,
		"DRAFT":                      1,
		"PUBLISHED":                  2,
		"REVIEWING":                  3,
		"REJECTED":                   4,
		"DELETED":                    5,
	}
)

func (x ArticleStatus) Enum() *ArticleStatus {
	p := new(ArticleStatus)
	*p = x
	return p
}

func (x ArticleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_article_proto_enumTypes[0].Descriptor()
}

func (ArticleStatus) Type() protoreflect.EnumType {
	return &file_proto_article_proto_enumTypes[0]
}

func (x ArticleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleStatus.Descriptor instead.
func (ArticleStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{0}
}

// 文章核心结构体（轻量 Markdown 格式，元数据+正文都存在 PG）
type Article struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                  // 文章唯一ID（雪花ID）
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                            // 文章标题
	Brief           string                 `protobuf:"bytes,3,opt,name=brief,proto3" json:"brief,omitempty"`                                            // 文章摘要（自动截取/手动填写，用于列表展示）
	MarkdownContent string                 `protobuf:"bytes,4,opt,name=markdown_content,json=markdownContent,proto3" json:"markdown_content,omitempty"` // 轻量 Markdown 正文（约束格式：标题、列表、图片链接、引用）
	CoverImageUrl   string                 `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`     // 封面图URL（用OSS/MinIO存储，仅存URL）
	ManualTypeTag   string                 `protobuf:"bytes,6,opt,name=manual_type_tag,json=manualTypeTag,proto3" json:"manual_type_tag,omitempty"`     // 手动一级标签（如：游戏评测/攻略/杂谈）
	SecondaryTags   []string               `protobuf:"bytes,7,rep,name=secondary_tags,json=secondaryTags,proto3" json:"secondary_tags,omitempty"`       // 二级标签（如：《黑神话：悟空》/PS5/Steam）
	AuthorId        string                 `protobuf:"bytes,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`                      // 作者ID（关联用户服务）
	CreateTime      int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`               // 创建时间（毫秒时间戳）
	UpdateTime      int64                  `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`              // 更新时间（毫秒时间戳）
	Status          ArticleStatus          `protobuf:"varint,11,opt,name=status,proto3,enum=article.ArticleStatus" json:"status,omitempty"`             // 文章状态
	// 社区互动数据（直接存在PG，高频更新可缓存）
	ViewCount     int32             `protobuf:"varint,12,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`                                                                    // 阅读量
	LikeCount     int32             `protobuf:"varint,13,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`                                                                    // 点赞数
	CommentCount  int32             `protobuf:"varint,14,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`                                                           // 评论数
	ShareCount    int32             `protobuf:"varint,15,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`                                                                 // 分享数
	ExtInfo       map[string]string `protobuf:"bytes,16,rep,name=ext_info,json=extInfo,proto3" json:"ext_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展字段（如：关联游戏ID/活动ID）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_proto_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *Article) GetMarkdownContent() string {
	if x != nil {
		return x.MarkdownContent
	}
	return ""
}

func (x *Article) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *Article) GetManualTypeTag() string {
	if x != nil {
		return x.ManualTypeTag
	}
	return ""
}

func (x *Article) GetSecondaryTags() []string {
	if x != nil {
		return x.SecondaryTags
	}
	return nil
}

func (x *Article) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Article) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Article) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Article) GetStatus() ArticleStatus {
	if x != nil {
		return x.Status
	}
	return ArticleStatus_ARTICLE_STATUS_UNSPECIFIED
}

func (x *Article) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Article) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Article) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Article) GetShareCount() int32 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *Article) GetExtInfo() map[string]string {
	if x != nil {
		return x.ExtInfo
	}
	return nil
}

// 创建文章请求
type CreateArticleReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                              // 标题
	Brief           *string                `protobuf:"bytes,2,opt,name=brief,proto3,oneof" json:"brief,omitempty"`                                        // 摘要（可选，自动截取正文前150字）
	MarkdownContent string                 `protobuf:"bytes,3,opt,name=markdown_content,json=markdownContent,proto3" json:"markdown_content,omitempty"`   // 轻量 Markdown 正文
	CoverImageUrl   *string                `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"` // 封面图URL（可选）
	ManualTypeTag   string                 `protobuf:"bytes,5,opt,name=manual_type_tag,json=manualTypeTag,proto3" json:"manual_type_tag,omitempty"`       // 一级标签
	SecondaryTags   []string               `protobuf:"bytes,6,rep,name=secondary_tags,json=secondaryTags,proto3" json:"secondary_tags,omitempty"`         // 二级标签
	AuthorId        string                 `protobuf:"bytes,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`                        // 作者ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateArticleReq) Reset() {
	*x = CreateArticleReq{}
	mi := &file_proto_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleReq) ProtoMessage() {}

func (x *CreateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleReq.ProtoReflect.Descriptor instead.
func (*CreateArticleReq) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleReq) GetBrief() string {
	if x != nil && x.Brief != nil {
		return *x.Brief
	}
	return ""
}

func (x *CreateArticleReq) GetMarkdownContent() string {
	if x != nil {
		return x.MarkdownContent
	}
	return ""
}

func (x *CreateArticleReq) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *CreateArticleReq) GetManualTypeTag() string {
	if x != nil {
		return x.ManualTypeTag
	}
	return ""
}

func (x *CreateArticleReq) GetSecondaryTags() []string {
	if x != nil {
		return x.SecondaryTags
	}
	return nil
}

func (x *CreateArticleReq) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

// 创建文章响应
type CreateArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResp) Reset() {
	*x = CreateArticleResp{}
	mi := &file_proto_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResp) ProtoMessage() {}

func (x *CreateArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResp.ProtoReflect.Descriptor instead.
func (*CreateArticleResp) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleResp) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

// 获取文章详情请求
type GetArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章ID
	IncrView      bool                   `protobuf:"varint,2,opt,name=incr_view,json=incrView,proto3" json:"incr_view,omitempty"`   // 是否增加阅读量（详情页传true，其他场景传false）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleReq) Reset() {
	*x = GetArticleReq{}
	mi := &file_proto_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReq) ProtoMessage() {}

func (x *GetArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReq.ProtoReflect.Descriptor instead.
func (*GetArticleReq) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *GetArticleReq) GetIncrView() bool {
	if x != nil {
		return x.IncrView
	}
	return false
}

// 获取文章详情响应
type GetArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"` // 文章完整数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResp) Reset() {
	*x = GetArticleResp{}
	mi := &file_proto_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResp) ProtoMessage() {}

func (x *GetArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResp.ProtoReflect.Descriptor instead.
func (*GetArticleResp) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleResp) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// 更新文章请求
type UpdateArticleReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ArticleId       string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章ID（必传）
	Title           *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Brief           *string                `protobuf:"bytes,3,opt,name=brief,proto3,oneof" json:"brief,omitempty"`
	MarkdownContent *string                `protobuf:"bytes,4,opt,name=markdown_content,json=markdownContent,proto3,oneof" json:"markdown_content,omitempty"`
	CoverImageUrl   *string                `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"`
	ManualTypeTag   *string                `protobuf:"bytes,6,opt,name=manual_type_tag,json=manualTypeTag,proto3,oneof" json:"manual_type_tag,omitempty"`
	SecondaryTags   []string               `protobuf:"bytes,7,rep,name=secondary_tags,json=secondaryTags,proto3" json:"secondary_tags,omitempty"`
	Status          *ArticleStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=article.ArticleStatus,oneof" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateArticleReq) Reset() {
	*x = UpdateArticleReq{}
	mi := &file_proto_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReq) ProtoMessage() {}

func (x *UpdateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReq.ProtoReflect.Descriptor instead.
func (*UpdateArticleReq) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *UpdateArticleReq) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateArticleReq) GetBrief() string {
	if x != nil && x.Brief != nil {
		return *x.Brief
	}
	return ""
}

func (x *UpdateArticleReq) GetMarkdownContent() string {
	if x != nil && x.MarkdownContent != nil {
		return *x.MarkdownContent
	}
	return ""
}

func (x *UpdateArticleReq) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *UpdateArticleReq) GetManualTypeTag() string {
	if x != nil && x.ManualTypeTag != nil {
		return *x.ManualTypeTag
	}
	return ""
}

func (x *UpdateArticleReq) GetSecondaryTags() []string {
	if x != nil {
		return x.SecondaryTags
	}
	return nil
}

func (x *UpdateArticleReq) GetStatus() ArticleStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ArticleStatus_ARTICLE_STATUS_UNSPECIFIED
}

// 更新文章响应
type UpdateArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResp) Reset() {
	*x = UpdateArticleResp{}
	mi := &file_proto_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResp) ProtoMessage() {}

func (x *UpdateArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResp.ProtoReflect.Descriptor instead.
func (*UpdateArticleResp) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateArticleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 删除文章请求
type DeleteArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`    // 文章ID
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作人ID（作者/管理员）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleReq) Reset() {
	*x = DeleteArticleReq{}
	mi := &file_proto_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleReq) ProtoMessage() {}

func (x *DeleteArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleReq.ProtoReflect.Descriptor instead.
func (*DeleteArticleReq) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *DeleteArticleReq) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

// 删除文章响应
type DeleteArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResp) Reset() {
	*x = DeleteArticleResp{}
	mi := &file_proto_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResp) ProtoMessage() {}

func (x *DeleteArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResp.ProtoReflect.Descriptor instead.
func (*DeleteArticleResp) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteArticleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 文章列表查询请求（社区核心场景：首页/标签页/个人主页）
type ListArticlesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManualTypeTag *string                `protobuf:"bytes,1,opt,name=manual_type_tag,json=manualTypeTag,proto3,oneof" json:"manual_type_tag,omitempty"` // 按一级标签筛选
	SecondaryTag  *string                `protobuf:"bytes,2,opt,name=secondary_tag,json=secondaryTag,proto3,oneof" json:"secondary_tag,omitempty"`      // 按二级标签筛选
	RelatedGameId *string                `protobuf:"bytes,3,opt,name=related_game_id,json=relatedGameId,proto3,oneof" json:"related_game_id,omitempty"` // 按关联游戏筛选
	AuthorId      *string                `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3,oneof" json:"author_id,omitempty"`                  // 按作者筛选
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`                                               // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                       // 每页数量
	SortBy        string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                              // 排序字段（create_time/like_count/comment_count）
	Desc          bool                   `protobuf:"varint,8,opt,name=desc,proto3" json:"desc,omitempty"`                                               // 是否降序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesReq) Reset() {
	*x = ListArticlesReq{}
	mi := &file_proto_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesReq) ProtoMessage() {}

func (x *ListArticlesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesReq.ProtoReflect.Descriptor instead.
func (*ListArticlesReq) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{9}
}

func (x *ListArticlesReq) GetManualTypeTag() string {
	if x != nil && x.ManualTypeTag != nil {
		return *x.ManualTypeTag
	}
	return ""
}

func (x *ListArticlesReq) GetSecondaryTag() string {
	if x != nil && x.SecondaryTag != nil {
		return *x.SecondaryTag
	}
	return ""
}

func (x *ListArticlesReq) GetRelatedGameId() string {
	if x != nil && x.RelatedGameId != nil {
		return *x.RelatedGameId
	}
	return ""
}

func (x *ListArticlesReq) GetAuthorId() string {
	if x != nil && x.AuthorId != nil {
		return *x.AuthorId
	}
	return ""
}

func (x *ListArticlesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArticlesReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListArticlesReq) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// 文章列表查询响应
type ListArticlesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`                  // 文章列表（仅返回列表展示所需字段，可在服务层裁剪）
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总条数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResp) Reset() {
	*x = ListArticlesResp{}
	mi := &file_proto_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResp) ProtoMessage() {}

func (x *ListArticlesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResp.ProtoReflect.Descriptor instead.
func (*ListArticlesResp) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{10}
}

func (x *ListArticlesResp) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListArticlesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListArticlesResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ////////////////// hotspot / like /////////////////////
type LikeArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID (?)
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                           // 1=点赞, 2=取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleReq) Reset() {
	*x = LikeArticleReq{}
	mi := &file_proto_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleReq) ProtoMessage() {}

func (x *LikeArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleReq.ProtoReflect.Descriptor instead.
func (*LikeArticleReq) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{11}
}

func (x *LikeArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *LikeArticleReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LikeArticleReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type LikeArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int32                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"` // 点赞数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleResp) Reset() {
	*x = LikeArticleResp{}
	mi := &file_proto_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleResp) ProtoMessage() {}

func (x *LikeArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleResp.ProtoReflect.Descriptor instead.
func (*LikeArticleResp) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{12}
}

func (x *LikeArticleResp) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

var File_proto_article_proto protoreflect.FileDescriptor

const file_proto_article_proto_rawDesc = "" +
	"\n" +
	"\x13proto/article.proto\x12\aarticle\"\xf0\x04\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05brief\x18\x03 \x01(\tR\x05brief\x12)\n" +
	"\x10markdown_content\x18\x04 \x01(\tR\x0fmarkdownContent\x12&\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tR\rcoverImageUrl\x12&\n" +
	"\x0fmanual_type_tag\x18\x06 \x01(\tR\rmanualTypeTag\x12%\n" +
	"\x0esecondary_tags\x18\a \x03(\tR\rsecondaryTags\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\tR\bauthorId\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\n" +
	" \x01(\x03R\n" +
	"updateTime\x12.\n" +
	"\x06status\x18\v \x01(\x0e2\x16.article.ArticleStatusR\x06status\x12\x1d\n" +
	"\n" +
	"view_count\x18\f \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\r \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x0e \x01(\x05R\fcommentCount\x12\x1f\n" +
	"\vshare_count\x18\x0f \x01(\x05R\n" +
	"shareCount\x128\n" +
	"\bext_info\x18\x10 \x03(\v2\x1d.article.Article.ExtInfoEntryR\aextInfo\x1a:\n" +
	"\fExtInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x02\n" +
	"\x10CreateArticleReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x19\n" +
	"\x05brief\x18\x02 \x01(\tH\x00R\x05brief\x88\x01\x01\x12)\n" +
	"\x10markdown_content\x18\x03 \x01(\tR\x0fmarkdownContent\x12+\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tH\x01R\rcoverImageUrl\x88\x01\x01\x12&\n" +
	"\x0fmanual_type_tag\x18\x05 \x01(\tR\rmanualTypeTag\x12%\n" +
	"\x0esecondary_tags\x18\x06 \x03(\tR\rsecondaryTags\x12\x1b\n" +
	"\tauthor_id\x18\a \x01(\tR\bauthorIdB\b\n" +
	"\x06_briefB\x12\n" +
	"\x10_cover_image_url\"2\n" +
	"\x11CreateArticleResp\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"K\n" +
	"\rGetArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1b\n" +
	"\tincr_view\x18\x02 \x01(\bR\bincrView\"<\n" +
	"\x0eGetArticleResp\x12*\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.article.ArticleR\aarticle\"\xa9\x03\n" +
	"\x10UpdateArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x19\n" +
	"\x05brief\x18\x03 \x01(\tH\x01R\x05brief\x88\x01\x01\x12.\n" +
	"\x10markdown_content\x18\x04 \x01(\tH\x02R\x0fmarkdownContent\x88\x01\x01\x12+\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tH\x03R\rcoverImageUrl\x88\x01\x01\x12+\n" +
	"\x0fmanual_type_tag\x18\x06 \x01(\tH\x04R\rmanualTypeTag\x88\x01\x01\x12%\n" +
	"\x0esecondary_tags\x18\a \x03(\tR\rsecondaryTags\x123\n" +
	"\x06status\x18\b \x01(\x0e2\x16.article.ArticleStatusH\x05R\x06status\x88\x01\x01B\b\n" +
	"\x06_titleB\b\n" +
	"\x06_briefB\x13\n" +
	"\x11_markdown_contentB\x12\n" +
	"\x10_cover_image_urlB\x12\n" +
	"\x10_manual_type_tagB\t\n" +
	"\a_status\"-\n" +
	"\x11UpdateArticleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x10DeleteArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\"-\n" +
	"\x11DeleteArticleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xdd\x02\n" +
	"\x0fListArticlesReq\x12+\n" +
	"\x0fmanual_type_tag\x18\x01 \x01(\tH\x00R\rmanualTypeTag\x88\x01\x01\x12(\n" +
	"\rsecondary_tag\x18\x02 \x01(\tH\x01R\fsecondaryTag\x88\x01\x01\x12+\n" +
	"\x0frelated_game_id\x18\x03 \x01(\tH\x02R\rrelatedGameId\x88\x01\x01\x12 \n" +
	"\tauthor_id\x18\x04 \x01(\tH\x03R\bauthorId\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x12\n" +
	"\x04desc\x18\b \x01(\bR\x04descB\x12\n" +
	"\x10_manual_type_tagB\x10\n" +
	"\x0e_secondary_tagB\x12\n" +
	"\x10_related_game_idB\f\n" +
	"\n" +
	"_author_id\"\x87\x01\n" +
	"\x10ListArticlesResp\x12,\n" +
	"\barticles\x18\x01 \x03(\v2\x10.article.ArticleR\barticles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\\\n" +
	"\x0eLikeArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\"0\n" +
	"\x0fLikeArticleResp\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x05R\tlikeCount*s\n" +
	"\rArticleStatus\x12\x1e\n" +
	"\x1aARTICLE_STATUS_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DRAFT\x10\x01\x12\r\n" +
	"\tPUBLISHED\x10\x02\x12\r\n" +
	"\tREVIEWING\x10\x03\x12\f\n" +
	"\bREJECTED\x10\x04\x12\v\n" +
	"\aDELETED\x10\x052\xae\x03\n" +
	"\x0eArticleService\x12F\n" +
	"\rCreateArticle\x12\x19.article.CreateArticleReq\x1a\x1a.article.CreateArticleResp\x12=\n" +
	"\n" +
	"GetArticle\x12\x16.article.GetArticleReq\x1a\x17.article.GetArticleResp\x12F\n" +
	"\rUpdateArticle\x12\x19.article.UpdateArticleReq\x1a\x1a.article.UpdateArticleResp\x12F\n" +
	"\rDeleteArticle\x12\x19.article.DeleteArticleReq\x1a\x1a.article.DeleteArticleResp\x12C\n" +
	"\fListArticles\x12\x18.article.ListArticlesReq\x1a\x19.article.ListArticlesResp\x12@\n" +
	"\vLikeArticle\x12\x17.article.LikeArticleReq\x1a\x18.article.LikeArticleRespB\x03Z\x01.b\x06proto3"

var (
	file_proto_article_proto_rawDescOnce sync.Once
	file_proto_article_proto_rawDescData []byte
)

func file_proto_article_proto_rawDescGZIP() []byte {
	file_proto_article_proto_rawDescOnce.Do(func() {
		file_proto_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_article_proto_rawDesc), len(file_proto_article_proto_rawDesc)))
	})
	return file_proto_article_proto_rawDescData
}

var file_proto_article_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_article_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_article_proto_goTypes = []any{
	(ArticleStatus)(0),        // 0: article.ArticleStatus
	(*Article)(nil),           // 1: article.Article
	(*CreateArticleReq)(nil),  // 2: article.CreateArticleReq
	(*CreateArticleResp)(nil), // 3: article.CreateArticleResp
	(*GetArticleReq)(nil),     // 4: article.GetArticleReq
	(*GetArticleResp)(nil),    // 5: article.GetArticleResp
	(*UpdateArticleReq)(nil),  // 6: article.UpdateArticleReq
	(*UpdateArticleResp)(nil), // 7: article.UpdateArticleResp
	(*DeleteArticleReq)(nil),  // 8: article.DeleteArticleReq
	(*DeleteArticleResp)(nil), // 9: article.DeleteArticleResp
	(*ListArticlesReq)(nil),   // 10: article.ListArticlesReq
	(*ListArticlesResp)(nil),  // 11: article.ListArticlesResp
	(*LikeArticleReq)(nil),    // 12: article.LikeArticleReq
	(*LikeArticleResp)(nil),   // 13: article.LikeArticleResp
	nil,                       // 14: article.Article.ExtInfoEntry
}
var file_proto_article_proto_depIdxs = []int32{
	0,  // 0: article.Article.status:type_name -> article.ArticleStatus
	14, // 1: article.Article.ext_info:type_name -> article.Article.ExtInfoEntry
	1,  // 2: article.GetArticleResp.article:type_name -> article.Article
	0,  // 3: article.UpdateArticleReq.status:type_name -> article.ArticleStatus
	1,  // 4: article.ListArticlesResp.articles:type_name -> article.Article
	2,  // 5: article.ArticleService.CreateArticle:input_type -> article.CreateArticleReq
	4,  // 6: article.ArticleService.GetArticle:input_type -> article.GetArticleReq
	6,  // 7: article.ArticleService.UpdateArticle:input_type -> article.UpdateArticleReq
	8,  // 8: article.ArticleService.DeleteArticle:input_type -> article.DeleteArticleReq
	10, // 9: article.ArticleService.ListArticles:input_type -> article.ListArticlesReq
	12, // 10: article.ArticleService.LikeArticle:input_type -> article.LikeArticleReq
	3,  // 11: article.ArticleService.CreateArticle:output_type -> article.CreateArticleResp
	5,  // 12: article.ArticleService.GetArticle:output_type -> article.GetArticleResp
	7,  // 13: article.ArticleService.UpdateArticle:output_type -> article.UpdateArticleResp
	9,  // 14: article.ArticleService.DeleteArticle:output_type -> article.DeleteArticleResp
	11, // 15: article.ArticleService.ListArticles:output_type -> article.ListArticlesResp
	13, // 16: article.ArticleService.LikeArticle:output_type -> article.LikeArticleResp
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_article_proto_init() }
func file_proto_article_proto_init() {
	if File_proto_article_proto != nil {
		return
	}
	file_proto_article_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_article_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_article_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_article_proto_rawDesc), len(file_proto_article_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_article_proto_goTypes,
		DependencyIndexes: file_proto_article_proto_depIdxs,
		EnumInfos:         file_proto_article_proto_enumTypes,
		MessageInfos:      file_proto_article_proto_msgTypes,
	}.Build()
	File_proto_article_proto = out.File
	file_proto_article_proto_goTypes = nil
	file_proto_article_proto_depIdxs = nil
}
