// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hotspot.proto

package hotspotservice

import (
	"context"

	"sea-try-go/service/hotspot/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentInfo     = __.CommentInfo
	CommentReq      = __.CommentReq
	CommentResp     = __.CommentResp
	Empty           = __.Empty
	IsLikedReq      = __.IsLikedReq
	IsLikedResp     = __.IsLikedResp
	LikeReq         = __.LikeReq
	LikeResp        = __.LikeResp
	ListCommentReq  = __.ListCommentReq
	ListCommentResp = __.ListCommentResp

	HotspotService interface {
		// 点赞/取消点赞
		ToggleLike(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error)
		// 查询是否点赞过
		IsLiked(ctx context.Context, in *IsLikedReq, opts ...grpc.CallOption) (*IsLikedResp, error)
		// 发表评论
		CreateComment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentResp, error)
		// 获取评论列表
		ListComments(ctx context.Context, in *ListCommentReq, opts ...grpc.CallOption) (*ListCommentResp, error)
	}

	defaultHotspotService struct {
		cli zrpc.Client
	}
)

func NewHotspotService(cli zrpc.Client) HotspotService {
	return &defaultHotspotService{
		cli: cli,
	}
}

// 点赞/取消点赞
func (m *defaultHotspotService) ToggleLike(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error) {
	client := __.NewHotspotServiceClient(m.cli.Conn())
	return client.ToggleLike(ctx, in, opts...)
}

// 查询是否点赞过
func (m *defaultHotspotService) IsLiked(ctx context.Context, in *IsLikedReq, opts ...grpc.CallOption) (*IsLikedResp, error) {
	client := __.NewHotspotServiceClient(m.cli.Conn())
	return client.IsLiked(ctx, in, opts...)
}

// 发表评论
func (m *defaultHotspotService) CreateComment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentResp, error) {
	client := __.NewHotspotServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

// 获取评论列表
func (m *defaultHotspotService) ListComments(ctx context.Context, in *ListCommentReq, opts ...grpc.CallOption) (*ListCommentResp, error) {
	client := __.NewHotspotServiceClient(m.cli.Conn())
	return client.ListComments(ctx, in, opts...)
}
