// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleLikesFieldNames          = builder.RawFieldNames(&ArticleLikes{}, true)
	articleLikesRows                = strings.Join(articleLikesFieldNames, ",")
	articleLikesRowsExpectAutoSet   = strings.Join(stringx.Remove(articleLikesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	articleLikesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(articleLikesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	articleLikesModel interface {
		Insert(ctx context.Context, data *ArticleLikes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ArticleLikes, error)
		FindOneByArticleIdUserId(ctx context.Context, articleId string, userId string) (*ArticleLikes, error)
		Update(ctx context.Context, data *ArticleLikes) error
		Delete(ctx context.Context, id int64) error
	}

	defaultArticleLikesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ArticleLikes struct {
		Id         int64     `db:"id"`
		ArticleId  string    `db:"article_id"`
		UserId     string    `db:"user_id"`
		CreateTime time.Time `db:"create_time"`
	}
)

func newArticleLikesModel(conn sqlx.SqlConn) *defaultArticleLikesModel {
	return &defaultArticleLikesModel{
		conn:  conn,
		table: `"public"."article_likes"`,
	}
}

func (m *defaultArticleLikesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultArticleLikesModel) FindOne(ctx context.Context, id int64) (*ArticleLikes, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", articleLikesRows, m.table)
	var resp ArticleLikes
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleLikesModel) FindOneByArticleIdUserId(ctx context.Context, articleId string, userId string) (*ArticleLikes, error) {
	var resp ArticleLikes
	query := fmt.Sprintf("select %s from %s where article_id = $1 and user_id = $2 limit 1", articleLikesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, articleId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleLikesModel) Insert(ctx context.Context, data *ArticleLikes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, articleLikesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ArticleId, data.UserId)
	return ret, err
}

func (m *defaultArticleLikesModel) Update(ctx context.Context, newData *ArticleLikes) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, articleLikesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ArticleId, newData.UserId)
	return err
}

func (m *defaultArticleLikesModel) tableName() string {
	return m.table
}
