// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: points.proto

package pointsservice

import (
	"context"

	"sea-try-go/service/points/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PointsReq  = __.PointsReq
	PointsResp = __.PointsResp

	PointsService interface {
		Points(ctx context.Context, in *PointsReq, opts ...grpc.CallOption) (*PointsResp, error)
	}

	defaultPointsService struct {
		cli zrpc.Client
	}
)

func NewPointsService(cli zrpc.Client) PointsService {
	return &defaultPointsService{
		cli: cli,
	}
}

func (m *defaultPointsService) Points(ctx context.Context, in *PointsReq, opts ...grpc.CallOption) (*PointsResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.Points(ctx, in, opts...)
}
