// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommentItem struct {
	Id           int64         `json:"id"`
	UserId       int64         `json:"user_id"`
	Content      string        `json:"content"`
	RootId       int64         `json:"root_id"`
	ParentId     int64         `json:"parent_id"`
	LikeCount    int64         `json:"like_count"`
	DislikeCount int64         `json:"dislike_count"`
	ReplyCount   int64         `json:"reply_count"`
	Attribute    int64         `json:"attribute"`
	State        int32         `json:"state"`
	CreatedAt    string        `json:"created_at"`
	Meta         string        `json:"meta"`
	Children     []CommentItem `json:"children"`
}

type CreateCommentReq struct {
	UserId     int64  `json:"user_id"`
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
	RootId     int64  `json:"root_id"`
	ParentId   int64  `json:"parent_id"`
	Content    string `json:"content"`
	Meta       string `json:"meta"`
}

type CreateCommentResp struct {
	Id           int64  `json:"id"`
	CreatedAt    string `json:"created_at"`
	SubjectCount int64  `json:"subject_count"`
}

type DeleteCommentReq struct {
	UserId     int64  `json:"user_id"`
	CommentId  int64  `json:"comment_id"`
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
}

type DeleteCommentResp struct {
	Success           bool  `json:"success"`
	SubjectTotalCount int64 `json:"subject_total_count"`
}

type GetCommentReq struct {
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
	SortType   int64  `json:"sort_type"`
	RootId     int64  `json:"root_id"`
	Page       int64  `json:"page"`
	PageSize   int64  `json:"page_size"`
}

type GetCommentResp struct {
	Comment []CommentItem `json:"comment"`
	Subject SubjectInfo   `json:"subject"`
}

type LikeCommentReq struct {
	UserId     int64  `json:"user_id"`
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
	CommentId  int64  `json:"comment_id"`
	ActionType int32  `json:"action_type"`
}

type LikeCommentResp struct {
	Success   bool  `json:"success"`
	LikeCount int64 `json:"like_count"`
}

type ManageCommentReq struct {
	UserId     int64  `json:"user_id"`
	CommentId  int64  `json:"comment_id"`
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
	ActionType int32  `json:"action_type"`
}

type ManageCommentResp struct {
	Success bool `json:"success"`
}

type ReportCommentReq struct {
	UserId     int64  `json:"user_id"`
	CommentId  int64  `json:"comment_id"`
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
	Reason     int32  `json:"reason"`
	Detail     string `json:"detail"`
}

type ReportCommentResp struct {
	Success bool `json:"success"`
}

type SubjectInfo struct {
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
	TotalCount int64  `json:"total_count"`
	RootCount  int64  `json:"root_count"`
	State      int32  `json:"state"`
	Attribute  int64  `json:"attribute"`
	OwnerId    int64  `json:"owner_id"`
}

type UpdateSubjectStateReq struct {
	UserId     int64  `json:"user_id"`
	TargetType string `json:"target_type"`
	TargetId   string `json:"target_id"`
	State      int32  `json:"state"`
}

type UpdateSubjectStateResp struct {
	Success bool `json:"success"`
}
