// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	task "sea-try-go/service/task/api/internal/handler/task"
	"sea-try-go/service/task/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/task/get",
				Handler: task.GetTaskHandler(serverCtx),
			},
		},
		rest.WithPrefix("/taskcenter/v1"),
	)
}
