// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentsFieldNames          = builder.RawFieldNames(&Comments{}, true)
	commentsRows                = strings.Join(commentsFieldNames, ",")
	commentsRowsExpectAutoSet   = strings.Join(stringx.Remove(commentsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	commentsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(commentsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	commentsModel interface {
		Insert(ctx context.Context, data *Comments) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Comments, error)
		Update(ctx context.Context, data *Comments) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCommentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Comments struct {
		Id         int64     `db:"id"`
		BizId      int64     `db:"biz_id"`
		UserId     int64     `db:"user_id"`
		Content    string    `db:"content"`
		ParentId   int64     `db:"parent_id"`
		RootId     int64     `db:"root_id"`
		Status     int64     `db:"status"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newCommentsModel(conn sqlx.SqlConn) *defaultCommentsModel {
	return &defaultCommentsModel{
		conn:  conn,
		table: `"public"."comments"`,
	}
}

func (m *defaultCommentsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommentsModel) FindOne(ctx context.Context, id int64) (*Comments, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", commentsRows, m.table)
	var resp Comments
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentsModel) Insert(ctx context.Context, data *Comments) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, commentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.BizId, data.UserId, data.Content, data.ParentId, data.RootId, data.Status)
	return ret, err
}

func (m *defaultCommentsModel) Update(ctx context.Context, data *Comments) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, commentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.BizId, data.UserId, data.Content, data.ParentId, data.RootId, data.Status)
	return err
}

func (m *defaultCommentsModel) tableName() string {
	return m.table
}
