// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likesFieldNames          = builder.RawFieldNames(&Likes{}, true)
	likesRows                = strings.Join(likesFieldNames, ",")
	likesRowsExpectAutoSet   = strings.Join(stringx.Remove(likesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	likesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(likesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	likesModel interface {
		Insert(ctx context.Context, data *Likes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Likes, error)
		FindOneByBizIdUserId(ctx context.Context, bizId int64, userId int64) (*Likes, error)
		Update(ctx context.Context, data *Likes) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLikesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Likes struct {
		Id         int64     `db:"id"`
		BizId      int64     `db:"biz_id"`
		UserId     int64     `db:"user_id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		Status     int64     `db:"status"`
	}
)

func newLikesModel(conn sqlx.SqlConn) *defaultLikesModel {
	return &defaultLikesModel{
		conn:  conn,
		table: `"public"."likes"`,
	}
}

func (m *defaultLikesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLikesModel) FindOne(ctx context.Context, id int64) (*Likes, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", likesRows, m.table)
	var resp Likes
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) FindOneByBizIdUserId(ctx context.Context, bizId int64, userId int64) (*Likes, error) {
	var resp Likes
	query := fmt.Sprintf("select %s from %s where biz_id = $1 and user_id = $2 limit 1", likesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, bizId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) Insert(ctx context.Context, data *Likes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, likesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.BizId, data.UserId, data.Status)
	return ret, err
}

func (m *defaultLikesModel) Update(ctx context.Context, newData *Likes) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, likesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.BizId, newData.UserId, newData.Status)
	return err
}

func (m *defaultLikesModel) tableName() string {
	return m.table
}
